/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { Activities } from '../model/activities';
// @ts-ignore
import { PostActivitiesBatch200Response } from '../model/postActivitiesBatch200Response';
// @ts-ignore
import { PostActivitiesBatchRequest } from '../model/postActivitiesBatchRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ActivitiesService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Delete activities subscription
     * Deletes a subscription to the activities resource. 
     * @endpoint delete /activities/streams/{streamId}/subscriptions/{subscriptionId}
     * @param streamId The stream identifier that contains the subscription. This is the unique identifier for the client\&#39;s stream obtained via &#x60;GET /stream&#x60;. 
     * @param subscriptionId The identifier of the subscription to act upon. This is the unique identifier to the subscription for a specific resource or type of event. This value is found as the last parameter of a &#x60;METASYS-SUBSCRIPTION-LOCATION&#x60; header returned for the original subscription request. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteActivitiesSubscription(streamId: string, subscriptionId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public deleteActivitiesSubscription(streamId: string, subscriptionId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public deleteActivitiesSubscription(streamId: string, subscriptionId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public deleteActivitiesSubscription(streamId: string, subscriptionId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (streamId === null || streamId === undefined) {
            throw new Error('Required parameter streamId was null or undefined when calling deleteActivitiesSubscription.');
        }
        if (subscriptionId === null || subscriptionId === undefined) {
            throw new Error('Required parameter subscriptionId was null or undefined when calling deleteActivitiesSubscription.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/activities/streams/${this.configuration.encodeParam({name: "streamId", value: streamId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/subscriptions/${this.configuration.encodeParam({name: "subscriptionId", value: subscriptionId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List activities
     * Retrieves a collection of activities.
     * @endpoint get /activities
     * @param activityType Limit the activities returned to a specific type 
     * @param includeDiscarded Determines whether discarded activities will be included in the results or be the only type of activity in the results. Discarded activities are those for which the &#x60;activityManagementStatus&#x60; is &#x60;discarded&#x60;.  This parameter can produce 3 different types of results.  - &#x60;true&#x60; - Return only discarded activities in the response. - &#x60;false&#x60; - Do not include any discarded activities in the response. - _missing_ - (default) Discarded status is ignored; both discarded and   non-discarded activities are returned. 
     * @param continuationToken Provide a token from a previous request to fetch the next set of results. Ignored for streaming subscriptions.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param startTime Only include results generated on or after this date-time.
     * @param endTime Only include results generated on or before this date-time.
     * @param equipment Filter by list of equipment identifiers.
     * @param object Filter by list of object identifiers.
     * @param space Filter by list of space identifiers.
     * @param priorityRange Includes only results within the specified alarm priority range, from 0 to 255 inclusive.
     * @param type Limits the alarms returned to specified types.   The acceptable values for the elements of this parameter come from the &#x60;alarmValueEnumSet&#x60; enumeration. Only the long name of the alarm value (for example, &#x60;alarmValueEnumSet.avHighLimit&#x60; instead of &#x60;avHighLimit&#x60;) is accepted. Find the definition of &#x60;alarmValueEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/alarmValueEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param includeAcknowledged Determines whether acknowledged alarms will be included in the results or be the only type of alarm in the results. Acknowledged alarms are those which have an &#x60;acknowledgedTime&#x60; value set.  This parameter can produce 3 different types of results.  - &#x60;true&#x60; - Return only acknowledged alarms in the response. - &#x60;false&#x60; - Do not include any acknowledged alarms in the response. - _missing_ - (default) Acknowledged status is ignored; both acknowledged   and non-acknowledged alarms are returned. 
     * @param includeAcknowledgementRequired Determines whether activities which can be acknowledged are included in the results. When the value is &#x60;true&#x60;, activities which can be acknowledged will be included in the results. When &#x60;false&#x60;, activities which can be acknowledged will not be included in the results.  The use of this parameter implies a filter of &#x60;activityType&#x3D;alarm&#x60; and the results will not include any audits. 
     * @param includeAcknowledgementNotRequired Determines whether activities which can not be acknowledged are included in the results. When the value is &#x60;true&#x60; then the results will include activities which cannot be acknowledged. When the value is &#x60;false&#x60; then the results will not include activities which cannot be acknowledged.  The use of this parameter implies a filter of &#x60;activityType&#x3D;alarm&#x60; and the results will not include any audits. 
     * @param category The authorization category of the requested activities.   The acceptable values for the elements of this parameter come from the &#x60;objectCategoryEnumSet&#x60; enumeration. Only the long name of the object category (for example, &#x60;objectCategoryEnumSet.hvacCategory&#x60; instead of &#x60;hvacCategory&#x60;) is accepted. Find the definition of &#x60;objectCategoryEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/objectCategoryEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param originApplication Filter by list of origin applications. The origin application property indicates which application in Metasys generated the audit message.   The acceptable values for the elements of this parameter come from the &#x60;auditOriginAppEnumSet&#x60; enumeration. Only the long name of the origin application (for example, &#x60;auditOriginAppEnumSet.deviceManagerAuditOriginApp&#x60; instead of &#x60;deviceManagerAuditOriginApp&#x60;) is accepted. Find the definition of &#x60;auditOriginAppEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/auditOriginAppEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param classLevel Filter by list of class levels. The class level of an audit indicates the class or family the audit belongs to. Typically, each level of audit provides additional detail about the system, with Diagnostic audits being the most verbose.  The Enabled Audit Level attribute (&#x60;attributeEnumSet.auditEnabledClasLev&#x60;) determines which audit levels the system generates. Therefore, be aware that there will be no audits to return if the Enabled Audit Level attribute is set too low to generate audits at the desired class level in this filter. This attribute is set per device (for audits generated on that device).   The acceptable values for the elements of this parameter come from the &#x60;auditClassesEnumSet&#x60; enumeration. Only the long name of the class level (for example, &#x60;auditClassesEnumSet.userActionAuditClass&#x60; instead of &#x60;userActionAuditClass&#x60;) is accepted. Find the definition of &#x60;auditClassesEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/auditClassesEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param actionType Filter by list of action types. The action type property indicates the user or system action performed.   The acceptable values for the elements of this parameter come from the &#x60;auditActionTypeEnumSet&#x60; enumeration. Only the long name of the action type (for example, &#x60;auditActionTypeEnumSet.writeAuditActionType&#x60; instead of &#x60;writeAuditActionType&#x60;) is accepted. Find the definition of &#x60;auditActionTypeEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/auditActionTypeEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param user Filter by list of users. The user property indicates which user initiated the action being audited. 
     * @param mETASYSSUBSCRIBE If present, subscribes the client for streaming events associated with the resource. The value of this header is a stream id obtained by opening a stream with _Get a stream_. The response will have a &#x60;METASYS-SUBSCRIPTION-LOCATION&#x60; header which identifies the created subscription.  **See also:**  - [Get a stream](#operation/getStream) 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getActivities(activityType?: Array<'alarm' | 'audit'>, includeDiscarded?: boolean, continuationToken?: string, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', startTime?: string, endTime?: string, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, originApplication?: Array<string>, classLevel?: Array<string>, actionType?: Array<string>, user?: Array<string>, mETASYSSUBSCRIBE?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<Activities>;
    public getActivities(activityType?: Array<'alarm' | 'audit'>, includeDiscarded?: boolean, continuationToken?: string, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', startTime?: string, endTime?: string, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, originApplication?: Array<string>, classLevel?: Array<string>, actionType?: Array<string>, user?: Array<string>, mETASYSSUBSCRIBE?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Activities>>;
    public getActivities(activityType?: Array<'alarm' | 'audit'>, includeDiscarded?: boolean, continuationToken?: string, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', startTime?: string, endTime?: string, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, originApplication?: Array<string>, classLevel?: Array<string>, actionType?: Array<string>, user?: Array<string>, mETASYSSUBSCRIBE?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Activities>>;
    public getActivities(activityType?: Array<'alarm' | 'audit'>, includeDiscarded?: boolean, continuationToken?: string, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', startTime?: string, endTime?: string, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, originApplication?: Array<string>, classLevel?: Array<string>, actionType?: Array<string>, user?: Array<string>, mETASYSSUBSCRIBE?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (activityType) {
            activityType.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'activityType');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeDiscarded, 'includeDiscarded');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>continuationToken, 'continuationToken');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startTime, 'startTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endTime, 'endTime');
        if (equipment) {
            equipment.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'equipment');
            })
        }
        if (object) {
            object.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'object');
            })
        }
        if (space) {
            space.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'space');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>priorityRange, 'priorityRange');
        if (type) {
            type.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'type');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledged, 'includeAcknowledged');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledgementRequired, 'includeAcknowledgementRequired');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledgementNotRequired, 'includeAcknowledgementNotRequired');
        if (category) {
            category.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'category');
            })
        }
        if (originApplication) {
            originApplication.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'originApplication');
            })
        }
        if (classLevel) {
            classLevel.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'classLevel');
            })
        }
        if (actionType) {
            actionType.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'actionType');
            })
        }
        if (user) {
            user.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'user');
            })
        }

        let localVarHeaders = this.defaultHeaders;
        if (mETASYSSUBSCRIBE !== undefined && mETASYSSUBSCRIBE !== null) {
            localVarHeaders = localVarHeaders.set('METASYS-SUBSCRIBE', String(mETASYSSUBSCRIBE));
        }

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/activities`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Activities>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Batch operations
     * Used to invoke multiple activity operations in a single HTTP request. In this version of the API, the only activity-related operations that can be used in a batch are listed below.  **See also**  - [Edit an audit](#operation/patchAudit) - [Add audit annotation](#operation/postAuditAnnotation) - [Edit an alarm](#operation/patchAlarm)  
     * @endpoint post /activities/batch
     * @param postActivitiesBatchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postActivitiesBatch(postActivitiesBatchRequest: PostActivitiesBatchRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<PostActivitiesBatch200Response>;
    public postActivitiesBatch(postActivitiesBatchRequest: PostActivitiesBatchRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PostActivitiesBatch200Response>>;
    public postActivitiesBatch(postActivitiesBatchRequest: PostActivitiesBatchRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PostActivitiesBatch200Response>>;
    public postActivitiesBatch(postActivitiesBatchRequest: PostActivitiesBatchRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (postActivitiesBatchRequest === null || postActivitiesBatchRequest === undefined) {
            throw new Error('Required parameter postActivitiesBatchRequest was null or undefined when calling postActivitiesBatch.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/activities/batch`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PostActivitiesBatch200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: postActivitiesBatchRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
