/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { Alarm } from '../model/alarm';
// @ts-ignore
import { AlarmAnnotations } from '../model/alarmAnnotations';
// @ts-ignore
import { DeviceAlarms } from '../model/deviceAlarms';
// @ts-ignore
import { ObjectAlarms } from '../model/objectAlarms';
// @ts-ignore
import { PatchAlarmRequest } from '../model/patchAlarmRequest';
// @ts-ignore
import { StandardErrorMessage } from '../model/standardErrorMessage';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class AlarmsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get an alarm
     * Retrieves the specified alarm.
     * @endpoint get /alarms/{alarmId}
     * @param alarmId The identifier of the alarm.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAlarm(alarmId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<Alarm>;
    public getAlarm(alarmId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Alarm>>;
    public getAlarm(alarmId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Alarm>>;
    public getAlarm(alarmId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (alarmId === null || alarmId === undefined) {
            throw new Error('Required parameter alarmId was null or undefined when calling getAlarm.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/alarms/${this.configuration.encodeParam({name: "alarmId", value: alarmId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Alarm>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get alarm annotations
     * Retrieves the collection of annotations available for the specified alarm.
     * @endpoint get /alarms/{alarmId}/annotations
     * @param alarmId The identifier of the alarm.
     * @param startTime Only include results generated on or after this date-time.
     * @param endTime Only include results generated on or before this date-time.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAlarmAnnotations(alarmId: string, startTime?: string, endTime?: string, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'user' | '-user', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<AlarmAnnotations>;
    public getAlarmAnnotations(alarmId: string, startTime?: string, endTime?: string, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'user' | '-user', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AlarmAnnotations>>;
    public getAlarmAnnotations(alarmId: string, startTime?: string, endTime?: string, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'user' | '-user', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AlarmAnnotations>>;
    public getAlarmAnnotations(alarmId: string, startTime?: string, endTime?: string, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'user' | '-user', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (alarmId === null || alarmId === undefined) {
            throw new Error('Required parameter alarmId was null or undefined when calling getAlarmAnnotations.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startTime, 'startTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endTime, 'endTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/alarms/${this.configuration.encodeParam({name: "alarmId", value: alarmId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/annotations`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AlarmAnnotations>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get alarms for a network device
     * Retrieves a collection of alarms for the specified network device.
     * @endpoint get /networkDevices/{networkDeviceId}/alarms
     * @param networkDeviceId The identifier of a network device.
     * @param startTime Only include results generated on or after this date-time.
     * @param endTime Only include results generated on or before this date-time.
     * @param priorityRange Includes only results within the specified alarm priority range, from 0 to 255 inclusive.
     * @param type Limits the alarms returned to specified types.   The acceptable values for the elements of this parameter come from the &#x60;alarmValueEnumSet&#x60; enumeration. Only the long name of the alarm value (for example, &#x60;alarmValueEnumSet.avHighLimit&#x60; instead of &#x60;avHighLimit&#x60;) is accepted. Find the definition of &#x60;alarmValueEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/alarmValueEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param includeAcknowledged Determines whether acknowledged alarms will be included in the results or be the only type of alarm in the results. Acknowledged alarms are those which have an &#x60;acknowledgedTime&#x60; value set.  This parameter can produce 3 different types of results.  - &#x60;true&#x60; - Return only acknowledged alarms in the response. - &#x60;false&#x60; - Do not include any acknowledged alarms in the response. - _missing_ - (default) Acknowledged status is ignored; both acknowledged   and non-acknowledged alarms are returned. 
     * @param includeDiscarded Determines whether discarded alarms will be included in the results or be the only type of alarm in the results. Discarded alarms are those for which the &#x60;activityManagementStatus&#x60; is &#x60;discarded&#x60;. This parameter can produce 3 different types of results.  - &#x60;true&#x60; - Return only discarded alarms in the response. - &#x60;false&#x60; - Do not include any discarded alarms in the response. - _missing_ - (default) Discarded status is ignored; both discarded and   non-discarded alarms are returned. 
     * @param includeAcknowledgementRequired Determines whether alarms which can be acknowledged are included in the results. When the value is &#x60;true&#x60;, alarms which can be acknowledged will be included in the results. When &#x60;false&#x60;, alarms which can be acknowledged will not be included in the results.
     * @param includeAcknowledgementNotRequired Determines whether alarms which can not be acknowledged are included in the results. When the value is &#x60;true&#x60; then the results will include alarms which cannot be acknowledged. When the value is &#x60;false&#x60; then the results will not include alarms which cannot be acknowledged.
     * @param equipment Filter by list of equipment identifiers.
     * @param object Filter by list of object identifiers.
     * @param space Filter by list of space identifiers.
     * @param category The authorization category of the requested activities.   The acceptable values for the elements of this parameter come from the &#x60;objectCategoryEnumSet&#x60; enumeration. Only the long name of the object category (for example, &#x60;objectCategoryEnumSet.hvacCategory&#x60; instead of &#x60;hvacCategory&#x60;) is accepted. Find the definition of &#x60;objectCategoryEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/objectCategoryEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNetworkDeviceAlarms(networkDeviceId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<DeviceAlarms>;
    public getNetworkDeviceAlarms(networkDeviceId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<DeviceAlarms>>;
    public getNetworkDeviceAlarms(networkDeviceId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<DeviceAlarms>>;
    public getNetworkDeviceAlarms(networkDeviceId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, equipment?: Array<string>, object?: Array<string>, space?: Array<string>, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (networkDeviceId === null || networkDeviceId === undefined) {
            throw new Error('Required parameter networkDeviceId was null or undefined when calling getNetworkDeviceAlarms.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startTime, 'startTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endTime, 'endTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>priorityRange, 'priorityRange');
        if (type) {
            type.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'type');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledged, 'includeAcknowledged');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeDiscarded, 'includeDiscarded');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledgementRequired, 'includeAcknowledgementRequired');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledgementNotRequired, 'includeAcknowledgementNotRequired');
        if (equipment) {
            equipment.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'equipment');
            })
        }
        if (object) {
            object.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'object');
            })
        }
        if (space) {
            space.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'space');
            })
        }
        if (category) {
            category.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'category');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices/${this.configuration.encodeParam({name: "networkDeviceId", value: networkDeviceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/alarms`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<DeviceAlarms>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get alarms for an object
     * Retrieves a collection of alarms for the specified object.
     * @endpoint get /objects/{objectId}/alarms
     * @param objectId The identifier of the object.
     * @param startTime Only include results generated on or after this date-time.
     * @param endTime Only include results generated on or before this date-time.
     * @param priorityRange Includes only results within the specified alarm priority range, from 0 to 255 inclusive.
     * @param type Limits the alarms returned to specified types.   The acceptable values for the elements of this parameter come from the &#x60;alarmValueEnumSet&#x60; enumeration. Only the long name of the alarm value (for example, &#x60;alarmValueEnumSet.avHighLimit&#x60; instead of &#x60;avHighLimit&#x60;) is accepted. Find the definition of &#x60;alarmValueEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/alarmValueEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param includeAcknowledged Determines whether acknowledged alarms will be included in the results or be the only type of alarm in the results. Acknowledged alarms are those which have an &#x60;acknowledgedTime&#x60; value set.  This parameter can produce 3 different types of results.  - &#x60;true&#x60; - Return only acknowledged alarms in the response. - &#x60;false&#x60; - Do not include any acknowledged alarms in the response. - _missing_ - (default) Acknowledged status is ignored; both acknowledged   and non-acknowledged alarms are returned. 
     * @param includeDiscarded Determines whether discarded alarms will be included in the results or be the only type of alarm in the results. Discarded alarms are those for which the &#x60;activityManagementStatus&#x60; is &#x60;discarded&#x60;. This parameter can produce 3 different types of results.  - &#x60;true&#x60; - Return only discarded alarms in the response. - &#x60;false&#x60; - Do not include any discarded alarms in the response. - _missing_ - (default) Discarded status is ignored; both discarded and   non-discarded alarms are returned. 
     * @param includeAcknowledgementRequired Determines whether alarms which can be acknowledged are included in the results. When the value is &#x60;true&#x60;, alarms which can be acknowledged will be included in the results. When &#x60;false&#x60;, alarms which can be acknowledged will not be included in the results.
     * @param includeAcknowledgementNotRequired Determines whether alarms which can not be acknowledged are included in the results. When the value is &#x60;true&#x60; then the results will include alarms which cannot be acknowledged. When the value is &#x60;false&#x60; then the results will not include alarms which cannot be acknowledged.
     * @param category The authorization category of the requested activities.   The acceptable values for the elements of this parameter come from the &#x60;objectCategoryEnumSet&#x60; enumeration. Only the long name of the object category (for example, &#x60;objectCategoryEnumSet.hvacCategory&#x60; instead of &#x60;hvacCategory&#x60;) is accepted. Find the definition of &#x60;objectCategoryEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/objectCategoryEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectAlarms(objectId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<ObjectAlarms>;
    public getObjectAlarms(objectId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ObjectAlarms>>;
    public getObjectAlarms(objectId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ObjectAlarms>>;
    public getObjectAlarms(objectId: string, startTime?: string, endTime?: string, priorityRange?: string, type?: Array<string>, includeAcknowledged?: boolean, includeDiscarded?: boolean, includeAcknowledgementRequired?: boolean, includeAcknowledgementNotRequired?: boolean, category?: Array<string>, page?: number, pageSize?: number, sort?: 'creationTime' | '-creationTime' | 'priority' | '-priority', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectAlarms.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startTime, 'startTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endTime, 'endTime');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>priorityRange, 'priorityRange');
        if (type) {
            type.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'type');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledged, 'includeAcknowledged');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeDiscarded, 'includeDiscarded');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledgementRequired, 'includeAcknowledgementRequired');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeAcknowledgementNotRequired, 'includeAcknowledgementNotRequired');
        if (category) {
            category.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'category');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/alarms`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ObjectAlarms>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Edit an alarm
     * Allows for acknowledging or discarding an alarm.
     * @endpoint patch /alarms/{alarmId}
     * @param alarmId The identifier of the alarm.
     * @param patchAlarmRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public patchAlarm(alarmId: string, patchAlarmRequest: PatchAlarmRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public patchAlarm(alarmId: string, patchAlarmRequest: PatchAlarmRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public patchAlarm(alarmId: string, patchAlarmRequest: PatchAlarmRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public patchAlarm(alarmId: string, patchAlarmRequest: PatchAlarmRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (alarmId === null || alarmId === undefined) {
            throw new Error('Required parameter alarmId was null or undefined when calling patchAlarm.');
        }
        if (patchAlarmRequest === null || patchAlarmRequest === undefined) {
            throw new Error('Required parameter patchAlarmRequest was null or undefined when calling patchAlarm.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/alarms/${this.configuration.encodeParam({name: "alarmId", value: alarmId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: patchAlarmRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
