export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './alarms.service';
import { AlarmsService } from './alarms.service';
export * from './audits.service';
import { AuditsService } from './audits.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './equipment.service';
import { EquipmentService } from './equipment.service';
export * from './networkDevices.service';
import { NetworkDevicesService } from './networkDevices.service';
export * from './objects.service';
import { ObjectsService } from './objects.service';
export * from './schemas.service';
import { SchemasService } from './schemas.service';
export * from './spaces.service';
import { SpacesService } from './spaces.service';
export * from './streaming.service';
import { StreamingService } from './streaming.service';
export * from './timeSeries.service';
import { TimeSeriesService } from './timeSeries.service';
export const APIS = [ActivitiesService, AlarmsService, AuditsService, AuthenticationService, EquipmentService, NetworkDevicesService, ObjectsService, SchemasService, SpacesService, StreamingService, TimeSeriesService];
