/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent, HttpParameterCodec, HttpContext
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { LoginRequest } from '../model/loginRequest';
// @ts-ignore
import { LoginResponse } from '../model/loginResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
    providedIn: 'root'
})
export class AuthenticationService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Request access token
     * Use this to request an access token that can be used for authentication on other API calls. The accessToken is sensitive information and must be kept private. Do not share your access token with others. 
     * @endpoint post /login
     * @param loginRequest Used to supply credentials for login.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createToken(loginRequest: LoginRequest, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<LoginResponse>;
    public createToken(loginRequest: LoginRequest, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<LoginResponse>>;
    public createToken(loginRequest: LoginRequest, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<LoginResponse>>;
    public createToken(loginRequest: LoginRequest, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (loginRequest === null || loginRequest === undefined) {
            throw new Error('Required parameter loginRequest was null or undefined when calling createToken.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/login`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LoginResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: loginRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Refresh a token
     * Use this operation to request a new token before the previous one expires.
     * @endpoint get /refreshToken
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getToken(observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<LoginResponse>;
    public getToken(observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<LoginResponse>>;
    public getToken(observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<LoginResponse>>;
    public getToken(observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/refreshToken`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<LoginResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
