/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { EquipmentItem } from '../model/equipmentItem';
// @ts-ignore
import { EquipmentItemsLegacy } from '../model/equipmentItemsLegacy';
// @ts-ignore
import { EquipmentPoints } from '../model/equipmentPoints';
// @ts-ignore
import { EquipmentTree } from '../model/equipmentTree';
// @ts-ignore
import { ErrorMessage } from '../model/errorMessage';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class EquipmentService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get equipment instances
     * This operation is deprecated starting with Metasys Release 15.0. Use [Get equipment tree](#tag/equipment/operation/getEquipmentTreeRoot) instead.  Retrieves a collection of equipment instances. 
     * @endpoint get /equipment
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public getEquipment(page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getEquipment(page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getEquipment(page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getEquipment(page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get equipment hosted by a network device
     * Retrieves the collection of equipment instances hosted by the specified network device or its children. A network device is considered to host an equipment if the equipment defines points that map to an attribute of any object contained on the network device.
     * @endpoint get /networkDevices/{networkDeviceId}/equipment
     * @param networkDeviceId The identifier of a network device.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEquipmentHostedByDevice(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getEquipmentHostedByDevice(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getEquipmentHostedByDevice(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getEquipmentHostedByDevice(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (networkDeviceId === null || networkDeviceId === undefined) {
            throw new Error('Required parameter networkDeviceId was null or undefined when calling getEquipmentHostedByDevice.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices/${this.configuration.encodeParam({name: "networkDeviceId", value: networkDeviceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/equipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get an equipment instance
     * Retrieves the specified equipment instance.
     * @endpoint get /equipment/{equipmentId}
     * @param equipmentId The identifier of the equipment instance.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEquipmentInstance(equipmentId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItem>;
    public getEquipmentInstance(equipmentId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItem>>;
    public getEquipmentInstance(equipmentId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItem>>;
    public getEquipmentInstance(equipmentId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getEquipmentInstance.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json',
            'application/vnd.metasysapi.v6'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItem>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List equipment points
     * Retrieves the collection of points defined for the specified equipment instance. Each point contains a mapping to an attribute on an object.
     * @endpoint get /equipment/{equipmentId}/points
     * @param equipmentId The identifier of the equipment instance.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEquipmentPoints(equipmentId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentPoints>;
    public getEquipmentPoints(equipmentId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentPoints>>;
    public getEquipmentPoints(equipmentId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentPoints>>;
    public getEquipmentPoints(equipmentId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getEquipmentPoints.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json',
            'application/vnd.metasysapi.v6'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/points`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentPoints>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get equipment serving a space
     * Use [Get equipment serving space](#tag/equipment/operation/getSpaceServingEquipment) instead. It performs the same operation but with a path that is more descriptive of its task.  Retrieves the collection of equipment that serve the specified space. 
     * @endpoint get /spaces/{spaceId}/equipment
     * @param spaceId The identifier of a space.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public getEquipmentServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getEquipmentServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getEquipmentServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getEquipmentServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getEquipmentServingSpace.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/${this.configuration.encodeParam({name: "spaceId", value: spaceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/equipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get equipment subtree*
     * &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;  Retrieves a subset of the equipment tree starting at the specified item to the specified depth. The item can be an equipment instance or a folder within the tree.
     * @endpoint get /equipment/tree/{objectId}
     * @param objectId Specifies the root of the subtree to return for this request. The &#x60;objectId&#x60; is the identifier of the object to retrieve (optionally along with 1 or more levels of descendants).
     * @param depth Specifies depth of the tree to return. For typical usage, a value or 1 or 2 is recommended. Use &#x60;-1&#x60; for unlimited depth to return the entire tree. 
     * @param excludeServed Specifies whether the response should exclude all equipment that is currently serving another piece of equipment or a particular space. Only equipment that is unassigned and not serving any space or equipment will be returned 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEquipmentSubtree(objectId: string, depth?: number, excludeServed?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentTree>;
    public getEquipmentSubtree(objectId: string, depth?: number, excludeServed?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentTree>>;
    public getEquipmentSubtree(objectId: string, depth?: number, excludeServed?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentTree>>;
    public getEquipmentSubtree(objectId: string, depth?: number, excludeServed?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getEquipmentSubtree.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>depth, 'depth');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>excludeServed, 'excludeServed');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json',
            'application/vnd.metasysapi.v6'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/tree/${this.configuration.encodeParam({name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentTree>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get equipment tree*
     * &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;  Retrieves the equipment tree from the root to the specified depth.
     * @endpoint get /equipment/tree
     * @param depth Specifies depth of the tree to return. For typical usage, a value or 1 or 2 is recommended. Use &#x60;-1&#x60; for unlimited depth to return the entire tree. 
     * @param excludeServed Specifies whether the response should exclude all equipment that is currently serving another piece of equipment or a particular space. Only equipment that is unassigned and not serving any space or equipment will be returned 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEquipmentTree(depth?: number, excludeServed?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentTree>;
    public getEquipmentTree(depth?: number, excludeServed?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentTree>>;
    public getEquipmentTree(depth?: number, excludeServed?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentTree>>;
    public getEquipmentTree(depth?: number, excludeServed?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>depth, 'depth');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>excludeServed, 'excludeServed');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/tree`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentTree>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get equipment served by equipment
     * This operation is deprecated starting with Metasys Release 15.0. Use [Get served by equipment](#tag/equipment/operation/getServedEquipment) instead. It performs the same operation but with a path that is more descriptive of its task.  Retrieves the equipment served by the specified equipment instance. 
     * @endpoint get /equipment/{equipmentId}/equipment
     * @param equipmentId The identifier of the equipment instance.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public getServedByEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getServedByEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getServedByEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getServedByEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getServedByEquipment.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/equipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get served by equipment*
     * &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;  Retrieves the equipment served by the specified equipment instance.
     * @endpoint get /equipment/{equipmentId}/servedEquipment
     * @param equipmentId The identifier of the equipment instance.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort When provided, the criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getServedEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getServedEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getServedEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getServedEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getServedEquipment.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/servedEquipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get equipment serving a space*
     * &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;  Retrieves the collection of equipment that serve the specified space.
     * @endpoint get /spaces/{spaceId}/servingEquipment
     * @param spaceId The identifier of a space.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort When provided, the criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpaceServingEquipment(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getSpaceServingEquipment(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getSpaceServingEquipment(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getSpaceServingEquipment(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getSpaceServingEquipment.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/${this.configuration.encodeParam({name: "spaceId", value: spaceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/servingEquipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get upstream equipment
     * Retrieves the collection of all upstream equipment serving the specified equipment instance, including directly serving equipment and equipment that further serve the directly serving equipment recursively.
     * @endpoint get /equipment/{equipmentId}/upstreamEquipment
     * @param equipmentId The identifier of the equipment instance.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUpstreamEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<EquipmentItemsLegacy>;
    public getUpstreamEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<EquipmentItemsLegacy>>;
    public getUpstreamEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<EquipmentItemsLegacy>>;
    public getUpstreamEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'type' | '-type', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getUpstreamEquipment.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/upstreamEquipment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<EquipmentItemsLegacy>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
