/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { NetworkDevice } from '../model/networkDevice';
// @ts-ignore
import { NetworkDevices } from '../model/networkDevices';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class NetworkDevicesService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Deletes a network device
     * Deletes an engine or a server which is a child device of the site director. Cannot be used to delete controllers, integrations, or the site director.  **Note:** The device must be offline for the operation to succeed. 
     * @endpoint delete /networkDevices/{networkDeviceId}
     * @param networkDeviceId The identifier of a network device.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteNetworkDevice(networkDeviceId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public deleteNetworkDevice(networkDeviceId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public deleteNetworkDevice(networkDeviceId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public deleteNetworkDevice(networkDeviceId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (networkDeviceId === null || networkDeviceId === undefined) {
            throw new Error('Required parameter networkDeviceId was null or undefined when calling deleteNetworkDevice.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices/${this.configuration.encodeParam({name: "networkDeviceId", value: networkDeviceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List network device children
     * Retrieves the collection of network devices that are children of the specified network device.
     * @endpoint get /networkDevices/{networkDeviceId}/networkDevices
     * @param networkDeviceId The identifier of a network device.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChildNetworkDevices(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<NetworkDevices>;
    public getChildNetworkDevices(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<NetworkDevices>>;
    public getChildNetworkDevices(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<NetworkDevices>>;
    public getChildNetworkDevices(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (networkDeviceId === null || networkDeviceId === undefined) {
            throw new Error('Required parameter networkDeviceId was null or undefined when calling getChildNetworkDevices.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices/${this.configuration.encodeParam({name: "networkDeviceId", value: networkDeviceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/networkDevices`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<NetworkDevices>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single network device
     * Retrieves the specified network device.
     * @endpoint get /networkDevices/{networkDeviceId}
     * @param networkDeviceId The identifier of a network device.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNetworkDevice(networkDeviceId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<NetworkDevice>;
    public getNetworkDevice(networkDeviceId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<NetworkDevice>>;
    public getNetworkDevice(networkDeviceId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<NetworkDevice>>;
    public getNetworkDevice(networkDeviceId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (networkDeviceId === null || networkDeviceId === undefined) {
            throw new Error('Required parameter networkDeviceId was null or undefined when calling getNetworkDevice.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices/${this.configuration.encodeParam({name: "networkDeviceId", value: networkDeviceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<NetworkDevice>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List network devices
     * Retrieves a collection of network devices.
     * @endpoint get /networkDevices
     * @param objectType The type of network device to return.  The &#x60;objectType&#x60; query parameter cannot be used in conjunction with the &#x60;classification&#x60; query parameter.   The acceptable values for this parameter come from the &#x60;objectTypeEnumSet&#x60; enumeration. Only the long name of the object type (for example, &#x60;objectTypeEnumSet.bacnetIntegrationClass&#x60; instead of &#x60;bacnetIntegrationClass&#x60;) is accepted. Find the definition of &#x60;objectTypeEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/objectTypeEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param classification The classification to filter devices on. One or more values are supported.  The &#x60;classification&#x60; query parameter cannot be used in conjunction with the &#x60;objectType&#x60; query parameter. 
     * @param includeIncomplete &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;\\ Set to true to include incomplete devices and servers in the response. An incomplete network device is one that has not yet synchronized its archive with the site director. As a result, these devices have minimal information available. When set to true, incomplete devices will be returned using the incompleteNetworkDevice schema. (You can use the _Sync Engine_ command on a network engine to force synchronization with the site director.) 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNetworkDevices(objectType?: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, includeIncomplete?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<NetworkDevices>;
    public getNetworkDevices(objectType?: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, includeIncomplete?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<NetworkDevices>>;
    public getNetworkDevices(objectType?: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, includeIncomplete?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<NetworkDevices>>;
    public getNetworkDevices(objectType?: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, includeIncomplete?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>objectType, 'objectType');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');
        if (classification) {
            classification.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'classification');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>includeIncomplete, 'includeIncomplete');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<NetworkDevices>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List network devices hosting an equipment instance
     * Retrieves the collection of network devices that host the specified equipment instance, along with the parents of those network devices. A network device hosts an equipment when the equipment defines points that map to an attribute of any object contained on the network device.
     * @endpoint get /equipment/{equipmentId}/networkDevices
     * @param equipmentId The identifier of the equipment instance.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param classification &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;\\ The classification to filter devices on. One or more values are supported.  The &#x60;classification&#x60; query parameter cannot be used in conjunction with the &#x60;objectType&#x60; query parameter. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNetworkDevicesHostingEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<NetworkDevices>;
    public getNetworkDevicesHostingEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<NetworkDevices>>;
    public getNetworkDevicesHostingEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<NetworkDevices>>;
    public getNetworkDevicesHostingEquipment(equipmentId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', classification?: Array<'device' | 'integration' | 'server' | 'controller'>, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getNetworkDevicesHostingEquipment.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');
        if (classification) {
            classification.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'classification');
            })
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/networkDevices`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<NetworkDevices>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List network devices serving a space
     * Retrieves the collection of network devices that serve the specified space. A space serves a network device when any equipment instance serving the space defines points that map to an attribute of any object contained on the network device.
     * @endpoint get /spaces/{spaceId}/networkDevices
     * @param spaceId The identifier of a space.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNetworkDevicesServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<NetworkDevices>;
    public getNetworkDevicesServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<NetworkDevices>>;
    public getNetworkDevicesServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<NetworkDevices>>;
    public getNetworkDevicesServingSpace(spaceId: string, page?: number, pageSize?: number, sort?: 'categoryId' | '-categoryId' | 'firmwareVersion' | '-firmwareVersion' | 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getNetworkDevicesServingSpace.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/${this.configuration.encodeParam({name: "spaceId", value: spaceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/networkDevices`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<NetworkDevices>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
