/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent, HttpParameterCodec, HttpContext
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { ErrorMessage } from '../model/errorMessage';
// @ts-ignore
import { GetObject200Response } from '../model/getObject200Response';
// @ts-ignore
import { GetObjectAttributeResponse } from '../model/getObjectAttributeResponse';
// @ts-ignore
import { GetObjectAttributes200Response } from '../model/getObjectAttributes200Response';
// @ts-ignore
import { GetObjectCommands200Response } from '../model/getObjectCommands200Response';
// @ts-ignore
import { GetObjectSupportedChildTypes200ResponseInner } from '../model/getObjectSupportedChildTypes200ResponseInner';
// @ts-ignore
import { GetObjectViews200Response } from '../model/getObjectViews200Response';
// @ts-ignore
import { GetObjectsResponse } from '../model/getObjectsResponse';
// @ts-ignore
import { PatchObjectRequest } from '../model/patchObjectRequest';
// @ts-ignore
import { Points } from '../model/points';
// @ts-ignore
import { PostObjectsBatch200Response } from '../model/postObjectsBatch200Response';
// @ts-ignore
import { PostObjectsBatchRequest } from '../model/postObjectsBatchRequest';
// @ts-ignore
import { PostObjectsRequest } from '../model/postObjectsRequest';
// @ts-ignore
import { PutCommandRequest } from '../model/putCommandRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
    providedIn: 'root'
})
export class ObjectsService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Delete an object
     * Deletes the specified object.  Not all objects can be deleted (not even by an administrator). Examine the &#x60;effectivePermissions&#x60; of an object to determine if it can be deleted by the current user. 
     * @endpoint delete /objects/{objectId}
     * @param objectId The identifier of the object.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteObject(objectId: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any>;
    public deleteObject(objectId: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<any>>;
    public deleteObject(objectId: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<any>>;
    public deleteObject(objectId: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling deleteObject.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List child objects
     * Returns the specified object and optionally one or more levels of the tree under the object. The default response is a tree representation. Set &#x60;flatten&#x3D;true&#x60; to flatten the tree into a list representation. 
     * @endpoint get /objects/{objectId}/objects
     * @param objectId Specifies the root of the subtree to return for this request. The &#x60;objectId&#x60; is the identifier of the object to retrieve (optionally along with 1 or more levels of descendants).
     * @param depth The depth of the tree to return. For typical usage, a value or 1 or 2 is recommended. Use &#x60;-1&#x60; for maximum depth.  The provided value is ignored if &#x60;pathTo&#x60;, &#x60;objectType&#x60;, or &#x60;classification&#x60; are specified. 
     * @param flatten A value of &#x60;true&#x60; indicates the response payload should be a flat list. A value of &#x60;false&#x60; (the default) indicates the response payload should be a tree with child objects nested under their parent object. While this parameter influences the shape of the response, it does not affect the content. The same set of objects is returned no matter the value of this parameter.
     * @param includeExtensions A value of &#x60;true&#x60; indicates that extension objects should be included in the result. A value of &#x60;false&#x60; (the default) indicates that they should not be included.  This parameter is ignored if &#x60;pathTo&#x60; is specified. 
     * @param pathTo This parameter filters the response down to just containing the object specified by this parameter, the object specified by &#x60;objectId&#x60; in the path, and the objects in between.  If this parameter is specified, then &#x60;depth&#x60;, &#x60;includeExtensions&#x60;, &#x60;objectType&#x60; and &#x60;classification&#x60; are ignored. 
     * @param objectType Type of objects to include in the response. This parameter may be repeated. To search for all AV and AI objects one would specify &#x60;/objects?objectType&#x3D;avClass&amp;objectType&#x3D;aiClass&#x60;.  The use of this parameter overrides &#x60;depth&#x60; to &#x60;-1&#x60; and &#x60;includeExtensions&#x60; to &#x60;true&#x60;.  It is an error to specify this parameter if &#x60;classification&#x60; is specified.  The response will include the specified object, the objects that match the &#x60;objectType&#x60; for the given &#x60;depth&#x60; and any objects in between (like folders and devices).   The acceptable values for the elements of this parameter come from the &#x60;objectTypeEnumSet&#x60; enumeration. It is acceptable to use the short name of the object type (for example, &#x60;avClass&#x60; instead of &#x60;objectTypeEnumSet.avClass&#x60;) because the enumeration set is known from context. Find the definition of &#x60;objectTypeEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/objectTypeEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param classification Filter objects to those with the specific classification. The use of this parameter overrides &#x60;depth&#x60; to &#x60;-1&#x60; and &#x60;includeExtensions&#x60; to &#x60;true&#x60;. It is an error to specify this parameter if &#x60;objectType&#x60; is specified.
     * @param includeEffectivePermissions Include the &#x60;effectivePermissions&#x60; property in the response payload. This property describes which objects in the response the current user can view, modify or delete. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChildObjects(objectId: string, depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, objectType?: Array<string>, classification?: Array<'object' | 'device' | 'integration' | 'controller' | 'point' | 'site' | 'navList' | 'extension' | 'folder' | 'reference' | 'server' | 'archive'>, includeEffectivePermissions?: boolean, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObjectsResponse>;
    public getChildObjects(objectId: string, depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, objectType?: Array<string>, classification?: Array<'object' | 'device' | 'integration' | 'controller' | 'point' | 'site' | 'navList' | 'extension' | 'folder' | 'reference' | 'server' | 'archive'>, includeEffectivePermissions?: boolean, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObjectsResponse>>;
    public getChildObjects(objectId: string, depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, objectType?: Array<string>, classification?: Array<'object' | 'device' | 'integration' | 'controller' | 'point' | 'site' | 'navList' | 'extension' | 'folder' | 'reference' | 'server' | 'archive'>, includeEffectivePermissions?: boolean, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObjectsResponse>>;
    public getChildObjects(objectId: string, depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, objectType?: Array<string>, classification?: Array<'object' | 'device' | 'integration' | 'controller' | 'point' | 'site' | 'navList' | 'extension' | 'folder' | 'reference' | 'server' | 'archive'>, includeEffectivePermissions?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getChildObjects.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>depth, 'depth');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>flatten, 'flatten');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeExtensions, 'includeExtensions');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>pathTo, 'pathTo');
        if (objectType) {
            objectType.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                    <any>element, 'objectType');
            })
        }
        if (classification) {
            classification.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                    <any>element, 'classification');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeEffectivePermissions, 'includeEffectivePermissions');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/objects`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get an object
     * Objects support one or more views. By default, this operation gets the default view of an object. For many objects this is the Focus View (identifier &#x60;viewNameEnumSet.focusView&#x60;). To see the list of views an object supports see List Views (&#x60;/objects/{objectId}/views&#x60;). To get a different view of an object specify a value for the &#x60;viewId&#x60; parameter.  **Licensing Restrictions**  Requires Monitoring and Commanding API license.  **See also:**  - [List Views](#operation/getObjectViews) for information on retrieving the   view collection of an object. 
     * @endpoint get /objects/{objectId}
     * @param objectId The identifier of the object.
     * @param viewId The view to retrieve.  This parameter is optional and if it is not specified the default view for the object will be returned. For many objects this is the Focus view (&#x60;focusView&#x60;).   The acceptable values for this parameter come from the &#x60;viewNameEnumSet&#x60; enumeration. It is acceptable to use the short name of the view (for example, &#x60;focusView&#x60; instead of &#x60;viewNameEnumSet.focusView&#x60;) because the enumeration set is known from context. Find the definition of &#x60;viewNameEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/viewNameEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param includeSchema Every object can have a unique schema. Set this parameter to &#x60;true&#x60; to include the schema for this object in the response payload.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObject(objectId: string, viewId?: string, includeSchema?: boolean, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObject200Response>;
    public getObject(objectId: string, viewId?: string, includeSchema?: boolean, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObject200Response>>;
    public getObject(objectId: string, viewId?: string, includeSchema?: boolean, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObject200Response>>;
    public getObject(objectId: string, viewId?: string, includeSchema?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObject.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>viewId, 'viewId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeSchema, 'includeSchema');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObject200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get attribute value
     * Returns an object payload containing the specified attribute. Invoke this operation with a valid &#x60;METASYS-SUBSCRIBE&#x60; header to create a subscription for changes to that attribute, rather than returning a value. The current value and any updates to the attribute are instead sent over the specified stream.  **Licensing Restrictions**  Requires Monitoring and Commanding API license.  **See also:**  - [Get a stream](#operation/getStream) - [Change of value subscriptions](#change-of-value-subscriptions) 
     * @endpoint get /objects/{objectId}/attributes/{attributeId}
     * @param objectId The identifier of the object.
     * @param attributeId The attribute to read.   The acceptable values for this parameter come from the &#x60;attributeEnumSet&#x60; enumeration. Only the short name of the attribute (for example, &#x60;presentValue&#x60; instead of &#x60;attributeEnumSet.presentValue&#x60;) is accepted. Find the definition of &#x60;attributeEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/attributeEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param includeSchema Set this parameter to &#x60;true&#x60; to include a schema in the response.
     * @param mETASYSSUBSCRIBE If present, subscribes the client for streaming events associated with the resource. The value of this header is a stream id obtained by opening a stream with _Get a stream_. The response will have a &#x60;METASYS-SUBSCRIPTION-LOCATION&#x60; header which identifies the created subscription.  **See also:**  - [Get a stream](#operation/getStream) 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectAttribute(objectId: string, attributeId: string, includeSchema?: boolean, mETASYSSUBSCRIBE?: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObjectAttributeResponse>;
    public getObjectAttribute(objectId: string, attributeId: string, includeSchema?: boolean, mETASYSSUBSCRIBE?: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObjectAttributeResponse>>;
    public getObjectAttribute(objectId: string, attributeId: string, includeSchema?: boolean, mETASYSSUBSCRIBE?: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObjectAttributeResponse>>;
    public getObjectAttribute(objectId: string, attributeId: string, includeSchema?: boolean, mETASYSSUBSCRIBE?: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectAttribute.');
        }
        if (attributeId === null || attributeId === undefined) {
            throw new Error('Required parameter attributeId was null or undefined when calling getObjectAttribute.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeSchema, 'includeSchema');

        let localVarHeaders = this.defaultHeaders;
        if (mETASYSSUBSCRIBE !== undefined && mETASYSSUBSCRIBE !== null) {
            localVarHeaders = localVarHeaders.set('METASYS-SUBSCRIBE', String(mETASYSSUBSCRIBE));
        }

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/attributes/${this.configuration.encodeParam({ name: "attributeId", value: attributeId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectAttributeResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List attributes of an object
     * Returns an object payload with a JSON schema that contains all of the properties of the object. Each property entry contains only a partial schema for that property. (To discover the full schema of an attribute use &#x60;/objects/{objectId}?includeSchema&#x3D;true&#x60; or &#x60;/objects/{objectId}/attributes/{attrId}?includeSchema&#x3D;true&#x60;  The item section of the payload will contain at most one attribute, the &#x60;defaultAttribute&#x60;. The item section will be completely missing if the object does not have a default attribute.  There will be no views or condition sections like a typical object payload. 
     * @endpoint get /objects/{objectId}/attributes
     * @param objectId The identifier of the object.
     * @param attributeFilter Specifies which subset of attributes to include.  Here are the possible values and their meaning:  - &#x60;all&#x60; - Include all attributes. This is the default. - &#x60;basic&#x60; - Include all attributes that have a &#x60;metasysType&#x60; of &#x60;bool&#x60;,   &#x60;enum&#x60;, &#x60;byte&#x60;, &#x60;short&#x60;, &#x60;ushort&#x60;, &#x60;long&#x60;, &#x60;ulong&#x60;, &#x60;float&#x60;, or   &#x60;double&#x60;. - &#x60;writableBasic&#x60; - Include all &#x60;basic&#x60; attributes that are also   writable. - &#x60;prioritizedBasic&#x60; - Include all &#x60;writableBasic&#x60; attributes that are   also prioritized. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectAttributes(objectId: string, attributeFilter?: 'all' | 'basic' | 'writableBasic' | 'prioritizedBasic', observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObjectAttributes200Response>;
    public getObjectAttributes(objectId: string, attributeFilter?: 'all' | 'basic' | 'writableBasic' | 'prioritizedBasic', observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObjectAttributes200Response>>;
    public getObjectAttributes(objectId: string, attributeFilter?: 'all' | 'basic' | 'writableBasic' | 'prioritizedBasic', observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObjectAttributes200Response>>;
    public getObjectAttributes(objectId: string, attributeFilter?: 'all' | 'basic' | 'writableBasic' | 'prioritizedBasic', observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectAttributes.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>attributeFilter, 'attributeFilter');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/attributes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectAttributes200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List commands
     * Returns a payload that lists all of the commands that an object supports. Each command entry has an &#x60;invokeUrl&#x60; property, which is the URL needed to invoke the command. In addition, each command entry has a &#x60;commandBodySchema&#x60; property, which is a JSON schema that describes the acceptable payload for the command. Commands are invoked using the HTTP method &#x60;PUT&#x60; along with the &#x60;invokeUrl&#x60; and acceptable body.  **Note:** Some objects, such as multi-state values (MV) and binary values (BV), may list a command that has a &#x60;commandSet&#x60; property and a property named &#x60;aggregateCommand&#x60; with a value of &#x60;true&#x60; instead of &#x60;invokeUrl&#x60;. This &#x60;commandSet&#x60; lists one or more commands. This entry is not a true command but rather provides a hint to graphical user interfaces on how they may want to group the commands of the &#x60;commandSet&#x60; under one command name. For example, an &#x60;MV&#x60; object lists a command with the identifier &#x60;commandIdEnumSet.adjustCommand&#x60;. This is not an actual command on an &#x60;MV&#x60;. Instead the actual commands that could be used to present this command in a UI are listed in the &#x60;commandSet&#x60; and they have identifiers like &#x60;commandIdEnumSet.multistate0Command&#x60;. The Metasys User Interface displays all of these commands as a single adjust command with the titles of the individual commands as the parameter to send.  **Licensing Restrictions**  Requires Monitoring and Commanding API license. 
     * @endpoint get /objects/{objectId}/commands
     * @param objectId The identifier of the object.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectCommands(objectId: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObjectCommands200Response>;
    public getObjectCommands(objectId: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObjectCommands200Response>>;
    public getObjectCommands(objectId: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObjectCommands200Response>>;
    public getObjectCommands(objectId: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectCommands.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/commands`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectCommands200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get object id
     * Use [Lookup object identifier](#operation/getObjectsIdentifiers) instead.  Finds the object identifier (the &#x60;id&#x60; property of an object) for the object with the specified fully qualified reference (&#x60;fqr&#x60;). 
     * @endpoint get /objectIdentifiers
     * @param fqr The fully qualified reference of an object. It refers to an object\&#39;s &#x60;itemReference&#x60; property.  Fully qualified references use characters that must be escaped when used as query parameters. Most HTTP libraries do this for you automatically. However, if you are using &#x60;curl&#x60; or PowerShell where you specify the full URL yourself you may need to be aware. For example, here is the URL to use with &#x60;curl&#x60; for a reference of &#x60;oas:oas/Programming.AV3&#x60;: &#x60;https://{hostname}/api/v6/objectIdentifiers?fqr&#x3D;oas%3Aoas%2FProgramming.AV3&#x60;  
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public getObjectIdentifier(fqr: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<string>;
    public getObjectIdentifier(fqr: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<string>>;
    public getObjectIdentifier(fqr: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<string>>;
    public getObjectIdentifier(fqr: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (fqr === null || fqr === undefined) {
            throw new Error('Required parameter fqr was null or undefined when calling getObjectIdentifier.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>fqr, 'fqr');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objectIdentifiers`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List object equipment points
     * Retrieves all equipment points mapped to attributes of this object.
     * @endpoint get /objects/{objectId}/points
     * @param objectId The identifier of the object.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectPoints(objectId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'equipmentName' | '-equipmentName' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<Points>;
    public getObjectPoints(objectId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'equipmentName' | '-equipmentName' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<Points>>;
    public getObjectPoints(objectId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'equipmentName' | '-equipmentName' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<Points>>;
    public getObjectPoints(objectId: string, page?: number, pageSize?: number, sort?: 'category' | '-category' | 'equipmentName' | '-equipmentName' | 'isDisplayData' | '-isDisplayData' | 'shortName' | '-shortName', observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectPoints.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/points`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Points>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List supported child types
     * Many objects support nested objects. The obvious examples of this are &#x60;folder&#x60; objects and &#x60;device&#x60; objects. Less obvious examples include objects like analog value and multi-state value objects (which can have child objects like integrations). This operation lists the types of objects that can be created under an object. 
     * @endpoint get /objects/{objectId}/supportedChildTypes
     * @param objectId The identifier of the object.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectSupportedChildTypes(objectId: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<Array<GetObjectSupportedChildTypes200ResponseInner>>;
    public getObjectSupportedChildTypes(objectId: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<Array<GetObjectSupportedChildTypes200ResponseInner>>>;
    public getObjectSupportedChildTypes(objectId: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<Array<GetObjectSupportedChildTypes200ResponseInner>>>;
    public getObjectSupportedChildTypes(objectId: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectSupportedChildTypes.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/supportedChildTypes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<GetObjectSupportedChildTypes200ResponseInner>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List the views of an object
     * Objects support one or more views. Each view of an object contains a logical grouping of the object\&#39;s attributes. This operation lists the collection of views that an object has.  Each entry in the response contains the &#x60;id&#x60; of a view, and also the absolute URL used to request that view. Use _Get an object_ (&#x60;/objects/{objectId}&#x60;) to request a specific view by specifying the desired &#x60;id&#x60; for the &#x60;viewId&#x60; query parameter.  **See also:**  - [Get an object](#operation/getObject) 
     * @endpoint get /objects/{objectId}/views
     * @param objectId The identifier of the object.
     * @param includeSchema Set this parameter to &#x60;true&#x60; to include a schema in the response.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectViews(objectId: string, includeSchema?: boolean, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObjectViews200Response>;
    public getObjectViews(objectId: string, includeSchema?: boolean, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObjectViews200Response>>;
    public getObjectViews(objectId: string, includeSchema?: boolean, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObjectViews200Response>>;
    public getObjectViews(objectId: string, includeSchema?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling getObjectViews.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeSchema, 'includeSchema');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/views`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectViews200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List objects
     * Returns the root object of the tree and, optionally, its children. The root object is the site object. The default response is a tree representation. Set &#x60;flatten&#x3D;true&#x60; to flatten the tree into a list representation. The number of levels returned depends on the value of the &#x60;depth&#x60; parameter. To get just the root of the tree use a depth of 0. Values of &#x60;depth&#x60; greater than 1 are not allowed on this endpoint. 
     * @endpoint get /objects
     * @param depth The depth of the tree to return. The provided value is ignored if &#x60;pathTo&#x60;, &#x60;objectType&#x60;, or &#x60;classification&#x60; are specified.
     * @param flatten A value of &#x60;true&#x60; indicates the response payload should be a flat list. A value of &#x60;false&#x60; (the default) indicates the response payload should be a tree with child objects nested under their parent object. While this parameter influences the shape of the response, it does not affect the content. The same set of objects is returned no matter the value of this parameter.
     * @param includeExtensions A value of &#x60;true&#x60; indicates that extension objects should be included in the result. A value of &#x60;false&#x60; (the default) indicates that they should not be included.  This parameter is ignored if &#x60;pathTo&#x60; is specified. 
     * @param pathTo This parameter causes the response to contain the object specified by this parameter, the root object, and the objects in between.  If this parameter is specified, then &#x60;depth&#x60; and &#x60;includeExtensions&#x60; are ignored. 
     * @param includeEffectivePermissions Include the &#x60;effectivePermissions&#x60; property in the response payload. This property describes which objects in the response the current user can view, modify or delete. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjects(depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, includeEffectivePermissions?: boolean, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<GetObjectsResponse>;
    public getObjects(depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, includeEffectivePermissions?: boolean, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<GetObjectsResponse>>;
    public getObjects(depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, includeEffectivePermissions?: boolean, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<GetObjectsResponse>>;
    public getObjects(depth?: number, flatten?: boolean, includeExtensions?: boolean, pathTo?: string, includeEffectivePermissions?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>depth, 'depth');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>flatten, 'flatten');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeExtensions, 'includeExtensions');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>pathTo, 'pathTo');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>includeEffectivePermissions, 'includeEffectivePermissions');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectsResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lookup object identifier
     * Finds the object identifier (the &#x60;id&#x60; property of an object) for the object with the specified fully qualified reference (&#x60;fqr&#x60;).
     * @endpoint get /objects/identifiers
     * @param fqr The fully qualified reference of an object. It refers to an object\&#39;s &#x60;itemReference&#x60; property.  Fully qualified references use characters that must be escaped when used as query parameters. Most HTTP libraries do this for you automatically. However, if you are using &#x60;curl&#x60; or PowerShell where you specify the full URL yourself you may need to be aware. For example, here is the URL to use with &#x60;curl&#x60; for a reference of &#x60;oas:oas/Programming.AV3&#x60;: &#x60;https://{hostname}/api/v6/objectIdentifiers?fqr&#x3D;oas%3Aoas%2FProgramming.AV3&#x60;  
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectsIdentifiers(fqr: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<string>;
    public getObjectsIdentifiers(fqr: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<string>>;
    public getObjectsIdentifiers(fqr: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<string>>;
    public getObjectsIdentifiers(fqr: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (fqr === null || fqr === undefined) {
            throw new Error('Required parameter fqr was null or undefined when calling getObjectsIdentifiers.');
        }

        let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>fqr, 'fqr');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/identifiers`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Edit an object
     * This operation modifies one or more attributes of an object. **Note:** attributes must be updated in whole. For example, if you wish to modify an attribute of &#x60;metasysType&#x60; &#x60;struct&#x60; which is modelled as a JSON &#x60;object&#x60; you must include all elements of the struct. It is undefined what might happen if you do not. The write could fail, the non-mentioned members may get their default value or something else. This applies to any attribute that has a JSON type of &#x60;array&#x60; or &#x60;object&#x60;. The entire attribute value must be written even if you only wish to change one part of the value.  The request body contains an &#x60;item&#x60; property which contains one or more properties and their new values.  The attributes of an object (and their schemas) can be discovered by looking at the different views of an object or by requesting all of the attributes.  **Licensing Restrictions**  Requires Monitoring and Commanding API license.  **See also:**  - [Get an object](#operation/getObject) - [List object views](#operation/getObjectViews) - [List object attributes](#operation/getObjectAttributes) 
     * @endpoint patch /objects/{objectId}
     * @param objectId The identifier of the object.
     * @param patchObjectRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public patchObject(objectId: string, patchObjectRequest: PatchObjectRequest, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any>;
    public patchObject(objectId: string, patchObjectRequest: PatchObjectRequest, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<any>>;
    public patchObject(objectId: string, patchObjectRequest: PatchObjectRequest, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<any>>;
    public patchObject(objectId: string, patchObjectRequest: PatchObjectRequest, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling patchObject.');
        }
        if (patchObjectRequest === null || patchObjectRequest === undefined) {
            throw new Error('Required parameter patchObjectRequest was null or undefined when calling patchObject.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: patchObjectRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create object
     * Creates a new object. Several things are needed to successfully create an object. You must know  - the type of object you want to create - if that object type is supported in the location you want to create it - what properties can be set on that type of object when creating it - what properties are required to be set.  Find the complete list of object types with the operation &#x60;GET /schemas/enums/objectTypeEnumSet&#x60;. To determine the specific set of objects that can be created in a location use _List supported child types_ (&#x60;GET /objects/{objectId}/supportedChildTypes&#x60;). To discover what object properties can be set and which are required when creating an object use _Get a schema for an object type_ (&#x60;GET /schemas/objectTypes/{objectType}&#x60;)  **See also:**  - [List objects](#operation/getObjects) and   [List child objects](#operation/getChildObjects) to discover the object   identifier of the parent object. - [Get enumeration](#operation/getEnumerationAsJson) to look up the   &#x60;objectTypeEnumSet&#x60; enumeration. - [List supported child types](#operation/getObjectSupportedChildTypes) to   discover the supported object types for a given parent object. - [Get a schema for an object type](#operation/getObjectTypeSchema) to   discover the schema of the specific object type. 
     * @endpoint post /objects
     * @param postObjectsRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postObjects(postObjectsRequest: PostObjectsRequest, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any>;
    public postObjects(postObjectsRequest: PostObjectsRequest, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<any>>;
    public postObjects(postObjectsRequest: PostObjectsRequest, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<any>>;
    public postObjects(postObjectsRequest: PostObjectsRequest, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (postObjectsRequest === null || postObjectsRequest === undefined) {
            throw new Error('Required parameter postObjectsRequest was null or undefined when calling postObjects.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: postObjectsRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Batch operations
     * This operation is used to invoke multiple operations in a single HTTP request. Often a batch request is more efficient than sending each individual operation in its own HTTP request.  In this version of the API, the only objects related operation that can be used in a batch is _Get attribute value_.  If this operation is invoked with a valid &#x60;METASYS-SUBSCRIBE&#x60; header it will cause a subscription to be created for the attributes in the request and rather than returning any values, the current values and any updates to the attributes will be sent over the specified stream.  &lt;!-- markdownlint-disable no-emphasis-as-heading --&gt;  **Licensing Restrictions**  Requires Monitoring and Commanding API license.  &lt;!-- markdownlint-enable no-emphasis-as-heading --&gt;  **See also:**  - [Get attribute value](#operation/getObjectAttributes) - [Get a stream](#operation/getStream) - [Change of value subscriptions](#change-of-value-subscriptions) - [Lookup object identifier](#operation/getObjectsIdentifiers)  
     * @endpoint post /objects/batch
     * @param postObjectsBatchRequest 
     * @param mETASYSSUBSCRIBE If present, subscribes the client for streaming events associated with the resource. The value of this header is a stream id obtained by opening a stream with _Get a stream_. The response will have a &#x60;METASYS-SUBSCRIPTION-LOCATION&#x60; header which identifies the created subscription.  **See also:**  - [Get a stream](#operation/getStream) 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postObjectsBatch(postObjectsBatchRequest: PostObjectsBatchRequest, mETASYSSUBSCRIBE?: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<PostObjectsBatch200Response>;
    public postObjectsBatch(postObjectsBatchRequest: PostObjectsBatchRequest, mETASYSSUBSCRIBE?: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<PostObjectsBatch200Response>>;
    public postObjectsBatch(postObjectsBatchRequest: PostObjectsBatchRequest, mETASYSSUBSCRIBE?: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<PostObjectsBatch200Response>>;
    public postObjectsBatch(postObjectsBatchRequest: PostObjectsBatchRequest, mETASYSSUBSCRIBE?: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (postObjectsBatchRequest === null || postObjectsBatchRequest === undefined) {
            throw new Error('Required parameter postObjectsBatchRequest was null or undefined when calling postObjectsBatch.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (mETASYSSUBSCRIBE !== undefined && mETASYSSUBSCRIBE !== null) {
            localVarHeaders = localVarHeaders.set('METASYS-SUBSCRIBE', String(mETASYSSUBSCRIBE));
        }

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/batch`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PostObjectsBatch200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: postObjectsBatchRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send command
     * Used to send a command to an object. The payloads of commands differ, but they share some similarities. To learn the specifics of the commands of an object use &#x60;List commands&#x60;.  **Licensing Restrictions**  Requires Monitoring and Commanding API license.  **See also:**  - [List commands](#operation/getObjectCommands) 
     * @endpoint put /objects/{objectId}/commands/{commandId}
     * @param objectId The identifier of the object.
     * @param commandId The identifier of the command to send.  The acceptable values for this parameter come from the &#x60;commandIdEnumSet&#x60; enumeration. It is acceptable to use the short name of the command identifier (for example, &#x60;adjustCommand&#x60; instead of &#x60;commandIdEnumSet.adjustCommand&#x60;) because the enumeration set is known from context. Find the definition of &#x60;commandIdEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/commandIdEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param putCommandRequest The body of a command is defined by the &#x60;commandBodySchema&#x60;. The &#x60;commandBodySchema&#x60; is a property of every command returned by the [List commands](#operation/getObjectCommands) operation. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putObjectCommand(objectId: string, commandId: string, putCommandRequest: PutCommandRequest, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any>;
    public putObjectCommand(objectId: string, commandId: string, putCommandRequest: PutCommandRequest, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<any>>;
    public putObjectCommand(objectId: string, commandId: string, putCommandRequest: PutCommandRequest, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<any>>;
    public putObjectCommand(objectId: string, commandId: string, putCommandRequest: PutCommandRequest, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean }): Observable<any> {
        if (objectId === null || objectId === undefined) {
            throw new Error('Required parameter objectId was null or undefined when calling putObjectCommand.');
        }
        if (commandId === null || commandId === undefined) {
            throw new Error('Required parameter commandId was null or undefined when calling putObjectCommand.');
        }
        if (putCommandRequest === null || putCommandRequest === undefined) {
            throw new Error('Required parameter putCommandRequest was null or undefined when calling putObjectCommand.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/objects/${this.configuration.encodeParam({ name: "objectId", value: objectId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}/commands/${this.configuration.encodeParam({ name: "commandId", value: commandId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined })}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: putCommandRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
