/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GetObjectTypeSchema200Response } from '../model/getObjectTypeSchema200Response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class SchemasService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get enumeration
     * This operation retrieves the specified enumeration as a JSON schema. The path of this operation appears in several schemas of object payloads.  To get a list of all enumerations fetch the &#x60;enumerationSetNamesEnumSet&#x60;:  &#x60;&#x60;&#x60;text GET /schemas/enums/enumerationSetNamesEnumSet &#x60;&#x60;&#x60;  **See also:**  - [Get an object](#operation/getObject) 
     * @endpoint get /schemas/enums/{enumId}
     * @param enumId The enumeration to retrieve.  The acceptable values for this parameter come from the &#x60;enumerationSetNamesEnumSet&#x60; enumeration. It is acceptable to use the short name of the value (for example, &#x60;writePriorityEnumSet&#x60; instead of &#x60;enumerationSetNamesEnumSet.writePriorityEnumSet&#x60;) because the enumeration set is known from context. Find the definition of &#x60;enumerationSetNamesEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/enumerationSetNamesEnumSet&#x60;. 
     * @param acceptLanguage The language to use for display text of enumeration name and members. If no language is specified the client\&#39;s default language as specified in their user profile will be used.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEnumerationAsJsonSchema(enumId: string, acceptLanguage?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<object>;
    public getEnumerationAsJsonSchema(enumId: string, acceptLanguage?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<object>>;
    public getEnumerationAsJsonSchema(enumId: string, acceptLanguage?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<object>>;
    public getEnumerationAsJsonSchema(enumId: string, acceptLanguage?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (enumId === null || enumId === undefined) {
            throw new Error('Required parameter enumId was null or undefined when calling getEnumerationAsJsonSchema.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            localVarHeaders = localVarHeaders.set('Accept-Language', String(acceptLanguage));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schemas/enums/${this.configuration.encodeParam({name: "enumId", value: enumId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<object>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get object type schema
     * This endpoint retrieves a schema for a specific &#x60;objectType&#x60;. The schema describes the properties that can be set when creating an object of the specific type. 
     * @endpoint get /schemas/objectTypes/{objectType}
     * @param objectType The type of object  The acceptable values for this parameter come from the &#x60;objectTypeEnumSet&#x60; enumeration. It is acceptable to use the short name of the object type (for example, &#x60;avClass&#x60; instead of &#x60;objectTypeEnumSet.avClass&#x60;) because the enumeration set is known from context. Find the definition of &#x60;objectTypeEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/objectTypeEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param parentId The object under which this new object will be created.
     * @param extendedProperty The attribute to extend.  Indicates which attribute of the parent object the extension should be linked to. Used only for extension objects (like alarm extensions).   The acceptable values for this parameter come from the &#x60;attributeEnumSet&#x60; enumeration. It is acceptable to use the short name of the attribute (for example, &#x60;presentValue&#x60; instead of &#x60;attributeEnumSet.presentValue&#x60;) because the enumeration set is known from context. Find the definition of &#x60;attributeEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/attributeEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getObjectTypeSchema(objectType: string, parentId: string, extendedProperty?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<GetObjectTypeSchema200Response>;
    public getObjectTypeSchema(objectType: string, parentId: string, extendedProperty?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetObjectTypeSchema200Response>>;
    public getObjectTypeSchema(objectType: string, parentId: string, extendedProperty?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetObjectTypeSchema200Response>>;
    public getObjectTypeSchema(objectType: string, parentId: string, extendedProperty?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (objectType === null || objectType === undefined) {
            throw new Error('Required parameter objectType was null or undefined when calling getObjectTypeSchema.');
        }
        if (parentId === null || parentId === undefined) {
            throw new Error('Required parameter parentId was null or undefined when calling getObjectTypeSchema.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>parentId, 'parentId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>extendedProperty, 'extendedProperty');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/schemas/objectTypes/${this.configuration.encodeParam({name: "objectType", value: objectType, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetObjectTypeSchema200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
