/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ErrorMessage } from '../model/errorMessage';
// @ts-ignore
import { SchemasSpace } from '../model/schemasSpace';
// @ts-ignore
import { Spaces } from '../model/spaces';
// @ts-ignore
import { SpacesInTree } from '../model/spacesInTree';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class SpacesService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get space children
     * This operation is deprecated starting with Metasys Release 15.0. Use [Get spaces subtree](#tag/spaces/operation/getSpaceTreeChildren) instead.  Retrieves the collection of spaces that are located within the specified space. 
     * @endpoint get /spaces/{spaceId}/spaces
     * @param spaceId The identifier of a space.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public getChildSpaces(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<Spaces>;
    public getChildSpaces(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Spaces>>;
    public getChildSpaces(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Spaces>>;
    public getChildSpaces(spaceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getChildSpaces.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/${this.configuration.encodeParam({name: "spaceId", value: spaceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spaces`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Spaces>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get spaces served by a network device
     * Retrieves the collection of spaces served by the specified network device. A space is served by a network device when any equipment instance serving the space defines points that map to an attribute of any object contained on the network device.
     * @endpoint get /networkDevices/{networkDeviceId}/spaces
     * @param networkDeviceId The identifier of a network device.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDeviceSpaces(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<Spaces>;
    public getDeviceSpaces(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Spaces>>;
    public getDeviceSpaces(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Spaces>>;
    public getDeviceSpaces(networkDeviceId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (networkDeviceId === null || networkDeviceId === undefined) {
            throw new Error('Required parameter networkDeviceId was null or undefined when calling getDeviceSpaces.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/networkDevices/${this.configuration.encodeParam({name: "networkDeviceId", value: networkDeviceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spaces`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Spaces>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get spaces served by an equipment instance
     * Retrieves the collection of spaces served by the specified equipment instance.
     * @endpoint get /equipment/{equipmentId}/spaces
     * @param equipmentId The identifier of the equipment instance.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEquipmentSpaces(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<Spaces>;
    public getEquipmentSpaces(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Spaces>>;
    public getEquipmentSpaces(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Spaces>>;
    public getEquipmentSpaces(equipmentId: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (equipmentId === null || equipmentId === undefined) {
            throw new Error('Required parameter equipmentId was null or undefined when calling getEquipmentSpaces.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/equipment/${this.configuration.encodeParam({name: "equipmentId", value: equipmentId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/spaces`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Spaces>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single space
     * Retrieves the specified space.
     * @endpoint get /spaces/{spaceId}
     * @param spaceId The identifier of a space.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpace(spaceId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<SchemasSpace>;
    public getSpace(spaceId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SchemasSpace>>;
    public getSpace(spaceId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SchemasSpace>>;
    public getSpace(spaceId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json' | 'application/vnd.metasysapi.v6', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getSpace.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json',
            'application/vnd.metasysapi.v6'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/${this.configuration.encodeParam({name: "spaceId", value: spaceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SchemasSpace>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get spaces subtree*
     * &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;  Retrieves the section of the spaces tree starting with a root at the specified tree. 
     * @endpoint get /spaces/tree/{spaceId}
     * @param spaceId The identifier of a space.
     * @param depth Specifies the depth of the tree to return. A depth of 0 returns only the the specified space. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpaceTreeChildren(spaceId: string, depth?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<SpacesInTree>;
    public getSpaceTreeChildren(spaceId: string, depth?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SpacesInTree>>;
    public getSpaceTreeChildren(spaceId: string, depth?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SpacesInTree>>;
    public getSpaceTreeChildren(spaceId: string, depth?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (spaceId === null || spaceId === undefined) {
            throw new Error('Required parameter spaceId was null or undefined when calling getSpaceTreeChildren.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>depth, 'depth');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/tree/${this.configuration.encodeParam({name: "spaceId", value: spaceId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SpacesInTree>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get spaces
     * This operation is deprecated starting with Metasys Release 15.0. Use [Get spaces tree](#tag/spaces/operation/getSpacesTreeRoot) instead.  Retrieves the collection of spaces. 
     * @endpoint get /spaces
     * @param type Type of space to return.   The acceptable values for this parameter come from the &#x60;spaceTypesEnumSet&#x60; enumeration. Only the long name of the space type (for example, &#x60;spaceTypesEnumSet.building&#x60; instead of &#x60;building&#x60;) is accepted. Find the definition of &#x60;spaceTypesEnumSet&#x60; at the relative URL of &#x60;/schemas/enums/spaceTypesEnumSet&#x60;.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     * @param page The page number of items to return.
     * @param pageSize The maximum number of items to return in the response.
     * @param sort The criteria to use when sorting results (see [rules](#section/Sorting-Rules)).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @deprecated
     */
    public getSpaces(type?: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<Spaces>;
    public getSpaces(type?: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Spaces>>;
    public getSpaces(type?: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Spaces>>;
    public getSpaces(type?: string, page?: number, pageSize?: number, sort?: 'itemReference' | '-itemReference' | 'name' | '-name' | 'typeId' | '-typeId', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>type, 'type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'pageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sort, 'sort');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Spaces>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get spaces tree*
     * &lt;span style&#x3D;\&quot;color: #92989b; font-size: 13px\&quot;&gt;RELEASE&lt;/span&gt;:&lt;span style&#x3D;\&quot;color: #d41f1c;\&quot;&gt; &lt;strong&gt;15.0&lt;/strong&gt;&lt;/span&gt;  Retrieves the spaces tree starting at the root to the specified depth.  
     * @endpoint get /spaces/tree
     * @param depth Specifies the depth of the tree to return. A depth of 0 returns only the the specified space. 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpacesTreeRoot(depth?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<SpacesInTree>;
    public getSpacesTreeRoot(depth?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<SpacesInTree>>;
    public getSpacesTreeRoot(depth?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<SpacesInTree>>;
    public getSpacesTreeRoot(depth?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.metasysapi.v6+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>depth, 'depth');

        let localVarHeaders = this.defaultHeaders;

        // authentication (Bearer-Authentication) required
        localVarHeaders = this.configuration.addCredentialToHeaders('Bearer-Authentication', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.metasysapi.v6+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/spaces/tree`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<SpacesInTree>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
