/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the ability for the current user to take action on a given activity. 
 */
export interface ActivitiesEffectivePermissionsInner { 
    /**
     * The ID of the activity that these permissions apply to.
     */
    id: string;
    /**
     * Indicates whether the current user can acknowledge the activity. This property will only be present for an alarm activity. 
     */
    canAcknowledge?: boolean;
    /**
     * Indicates whether the current user can discard the activity.
     */
    canDiscard: boolean;
    /**
     * Indicates whether the current user can annotate the activity. This property will only be present if the current platform supports annotations. 
     */
    canAnnotate?: boolean;
}

