/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space';
import { Equipment } from './equipment';
import { AuditActivity } from './auditActivity';
import { AuditActivityAudit } from './auditActivityAudit';
import { AlarmActivity } from './alarmActivity';
import { AlarmActivityAlarm } from './alarmActivityAlarm';


/**
 * @type ActivitiesItemsInner
 * @export
 */
export type ActivitiesItemsInner = AlarmActivity | AuditActivity;

