/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload sent periodically to indicate that one or more subscriptions exist for the current stream. 
 */
export interface ActivitiesStreamHeartbeat { 
    /**
     * Current server time in ISO8601 format
     */
    readonly currentTime: string;
    /**
     * List of all active subscriptionIds for this stream
     */
    subscriptionIds: Array<string>;
}

