/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivitiesItemsInner } from './activitiesItemsInner';
import { ActivitiesEffectivePermissionsInner } from './activitiesEffectivePermissionsInner';


export interface Activities { 
    /**
     * The total number of activities in the collection.
     */
    total: number;
    /**
     * Collection of activities.
     */
    items: Array<ActivitiesItemsInner>;
    /**
     * A collection of permissions that apply to the activities in `items`. 
     */
    effectivePermissions: Array<ActivitiesEffectivePermissionsInner>;
    /**
     * A link to the next set of results. This link contains the continuation token used to retrieve the next set. 
     */
    next: string | null;
    /**
     * A link to this list of activities.
     */
    self: string;
}

