/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlarmTriggerValueAllOfItem } from './alarmTriggerValueAllOfItem';


/**
 * The digital value of the attribute of the object on which the alarm was triggered. 
 */
export interface AlarmTriggerValue { 
    item: AlarmTriggerValueAllOfItem;
    schema: object;
}

