/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space';
import { Equipment } from './equipment';
import { AlarmBacnet } from './alarmBacnet';
import { AlarmAssociatedGraphic } from './alarmAssociatedGraphic';
import { AlarmTriggerValue } from './alarmTriggerValue';
import { NullableObjectReferenceDefinition } from './nullableObjectReferenceDefinition';


export interface Alarm { 
    /**
     * The identifier of the alarm.
     */
    id: string;
    /**
     * The fully qualified reference of the object.
     */
    itemReference: string;
    /**
     * The name of the object.
     */
    name: string;
    /**
     * A more detailed description of the triggered alarm, either describing the object that triggered the alarm or the alarm itself. 
     */
    description: string;
    /**
     * The activity management status of this item.  The values of this property are described as follows:  - `pending` - Indicates the activity has not yet been acted upon by a   user. - `acknowledged` - Indicates that the activity has been recognized and   viewed by a user. - `discarded` - Indicates that the activity has been acted upon or   deemed invalid by a user. 
     */
    activityManagementStatus: Alarm.ActivityManagementStatusEnum;
    /**
     * The date-time representing the time when this activity message was discarded. 
     */
    discardedTime: string | null;
    /**
     * The date-time for when the alarm was detected.
     */
    creationTime: string;
    /**
     * The date-time representing the time when this activity message was acknowledged. 
     */
    acknowledgedTime: string | null;
    /**
     * A link to the object from which this alarm was generated.
     */
    objectUrl: string;
    /**
     * The alarm message.
     */
    message: string;
    /**
     * Indicates whether the alarm can be acknowledged. You will get an error response if you attempt to acknowledge an alarm for which this property is `false`. 
     */
    isAckRequired: boolean;
    /**
     * The type of alarm.  The values for this property come from the `alarmValueEnumSet` enumeration. Find the definition of `alarmValueEnumSet` at the relative URL of `/schemas/enums/alarmValueEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    type: string;
    /**
     * The priority of the alarm.
     */
    priority: number;
    /**
     * The authorization category of the object when the alarm was generated.   The values for this property come from the `objectCategoryEnumSet` enumeration. Find the definition of `objectCategoryEnumSet` at the relative URL of `/schemas/enums/objectCategoryEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    category: string;
    /**
     * A link to the annotations available on the alarms.
     */
    annotationsUrl: string;
    /**
     * The total number of annotations associated with the alarm.
     */
    annotationsCount: number;
    /**
     * The total number of MVE Annotations associated with the alarm. 
     */
    signedAnnotationsCount?: number;
    /**
     * A link to this alarm.
     */
    self: string;
    triggerValue: AlarmTriggerValue;
    /**
     * The collection of spaces associated with the object on which the activity occurred. 
     */
    spaces?: Array<Space>;
    /**
     * The collection of equipment associated with the object on which the activity occurred. 
     */
    equipment?: Array<Equipment>;
    /**
     * Reference information to the object which generated the alarm. 
     */
    alarmGeneratorObject: NullableObjectReferenceDefinition | null;
    associatedGraphic: AlarmAssociatedGraphic | null;
    bacnet?: AlarmBacnet;
}
export namespace Alarm {
    export const ActivityManagementStatusEnum = {
        Pending: 'pending',
        Acknowledged: 'acknowledged',
        Discarded: 'discarded'
    } as const;
    export type ActivityManagementStatusEnum = typeof ActivityManagementStatusEnum[keyof typeof ActivityManagementStatusEnum];
}


