/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space';
import { Equipment } from './equipment';
import { AlarmActivityAlarm } from './alarmActivityAlarm';


/**
 * An alarm activity.
 */
export interface AlarmActivity { 
    /**
     * The identifier of the activity.
     */
    id: string;
    /**
     * The fully qualified reference of the object.
     */
    itemReference: string;
    /**
     * The name of the object.
     */
    objectName: string;
    /**
     * The identifier of the object that generated this activity.
     */
    objectId: string;
    /**
     * A link to the object that generated this activity.
     */
    objectUrl: string;
    /**
     * The date-time representing the time when a user discarded the activity. This property will only be present if the `activityManagementStatus` of the alarm or audit for the activity is `discarded`. 
     */
    discardedTime?: string | null;
    /**
     * The date-time for when the activity was detected.
     */
    creationTime: string;
    /**
     * The collection of spaces associated with the object on which the activity occurred. 
     */
    spaces?: Array<Space>;
    /**
     * The collection of equipment associated with the object on which the activity occurred. 
     */
    equipment?: Array<Equipment>;
    /**
     * The activity management status of this alarm. The values of this property are:  - `pending` - Indicates a user has not yet acted upon the alarm. - `acknowledged` - Indicates a user recognized and viewed the alarm. - `discarded` - Indicates a user acted upon or dismissed the alarm. 
     */
    activityManagementStatus: string;
    alarm: AlarmActivityAlarm;
}

