/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlarmActivityAlarmTriggerValueAllOfItem } from './alarmActivityAlarmTriggerValueAllOfItem';


/**
 * The value of the attribute of the object that triggered the alarm. 
 */
export interface AlarmActivityAlarmTriggerValue { 
    item: AlarmActivityAlarmTriggerValueAllOfItem;
    schema: object;
}

