/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlarmBacnetPropsTimestamp } from './alarmBacnetPropsTimestamp';
import { AlarmBacnetPropsDeviceId } from './alarmBacnetPropsDeviceId';
import { AlarmBacnetPropsNotificationClassId } from './alarmBacnetPropsNotificationClassId';
import { AlarmBacnetPropsObjectId } from './alarmBacnetPropsObjectId';


/**
 * <span style=\"color: #92989b; font-size: 13px\">RELEASES</span>:<span style=\"color: #d41f1c;\"> <strong>14.1 and 15.0</strong></span>\\ BACnet calls this type of record an event notification. The properties under this key are specific to BACnet event notifications. This property will only be present on a BACnet Advanced Workstation site. 
 */
export interface AlarmBacnet { 
    deviceId?: AlarmBacnetPropsDeviceId;
    objectId?: AlarmBacnetPropsObjectId;
    notificationClassId?: AlarmBacnetPropsNotificationClassId;
    timestamp?: AlarmBacnetPropsTimestamp;
    /**
     * The type of notification. This indicates if the notification is an alarm, an event or an acknowledgement. An example value is `bacNotifyTypeEnumSet.bacNotifyAlarm`   The values for this property come from the `bacNotifyTypeEnumSet` enumeration. Find the definition of `bacNotifyTypeEnumSet` at the relative URL of `/schemas/enums/bacNotifyTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    notifyType?: string;
}

