/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The signature associated with the activity.
 */
export interface AlarmAnnotationSignature { 
    /**
     * The full name of the person signing the annotation.
     */
    fullName?: string;
    /**
     * The reason for the action requiring an annotation.
     */
    reason?: string;
}

