/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectReferenceDefinition } from './objectReferenceDefinition';


/**
 * Reference information for the graphic associated with the alarm. 
 */
export interface AlarmAssociatedGraphic { 
    /**
     * Provides the fully qualified reference to the graphic associated with the alarm. 
     */
    reference: ObjectReferenceDefinition;
    /**
     * A link to the associated alarm graphic.
     */
    url: string;
    /**
     * The object alias to apply to the associated alarm graphic. 
     */
    alias: string;
    /**
     * A link to the associated alarm graphic resource, with the alias information included. 
     */
    aliasUrl: string;
}

