/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The notifier class that was responsible for distributing the alarm. 
 */
export interface AlarmBacnetPropsNotificationClassId { 
    /**
     * Will always be the Notification Class
     */
    bacnetObjectType?: AlarmBacnetPropsNotificationClassId.BacnetObjectTypeEnum;
    instance?: number;
}
export namespace AlarmBacnetPropsNotificationClassId {
    export const BacnetObjectTypeEnum = {
        ObjectTypeEnumSetBacNotificClass: 'objectTypeEnumSet.bacNotificClass'
    } as const;
    export type BacnetObjectTypeEnum = typeof BacnetObjectTypeEnum[keyof typeof BacnetObjectTypeEnum];
}


