/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type AlarmTriggerValueAllOfItem
 * @export
 */
export type AlarmTriggerValueAllOfItem = number | string;

