/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlarmAnnotationSignature } from './alarmAnnotationSignature';


export interface AlarmAnnotation { 
    /**
     * The identifier of the annotation.
     */
    id: number;
    /**
     * The annotation text.
     */
    text?: string | null;
    /**
     * The user who annotated the alarm.
     */
    user: string;
    /**
     * The date-time for when the annotation was created.
     */
    creationTime: string;
    signature?: AlarmAnnotationSignature | null;
    /**
     * The action on which the annotation was created. In the case that the annotation was not created during an action, the default value will be `none`.  The description for the values of this property are as follows:  - **`none`** - Indicates an annotation that was added as part of a   non-user action. - **`acknowledged`** - Indicates an annotation that was added as part of   an acknowledged action. - **`discarded`** - Indicates an annotation that was added as part of a   discarded action. - **`snoozed`** - Indicates an annotation that was added as part of a   snooze action. 
     */
    action: AlarmAnnotation.ActionEnum;
    /**
     * A link to the alarm.
     */
    alarmUrl: string;
}
export namespace AlarmAnnotation {
    export const ActionEnum = {
        None: 'none',
        Acknowledged: 'acknowledged',
        Discarded: 'discarded',
        Snoozed: 'snoozed'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


