/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SequenceNumber } from './sequenceNumber';
import { DateAndTime } from './dateAndTime';
import { Time } from './time';


/**
 * For devices with a clock this property will specify the time or date and time of the alarm. For devices without a clock this will convey a sequence number that indicates the relative ordering of alarms. A BACnet  Check for the existence of the properties `time`, `dateTime` and `sequenceNumber` to determine which is used for an instance of alarm. 
 */
/**
 * @type AlarmBacnetPropsTimestamp
 * For devices with a clock this property will specify the time or date and time of the alarm. For devices without a clock this will convey a sequence number that indicates the relative ordering of alarms. A BACnet  Check for the existence of the properties `time`, `dateTime` and `sequenceNumber` to determine which is used for an instance of alarm. 
 * @export
 */
export type AlarmBacnetPropsTimestamp = DateAndTime | SequenceNumber | Time;

