/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The BACoid of the device where the event initiated.
 */
export interface AlarmBacnetPropsDeviceId { 
    /**
     * The values for this property come from the `objectTypeEnumSet` enumeration. Find the definition of `objectTypeEnumSet` at the relative URL of `/schemas/enums/objectTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    bacnetObjectType?: string;
    instance?: number;
}

