/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataTypeMetaSchema } from './dataTypeMetaSchema';


/**
 * A variant data type that can hold a value of any of the built-in data types of the Metasys object model.
 */
export interface AnyDataTypeSchemaRequired { 
    item: any | null;
    schema: DataTypeMetaSchema;
}

