/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnyDataTypeSchemaRequired } from './anyDataTypeSchemaRequired';
import { DataTypeMetaSchema } from './dataTypeMetaSchema';


/**
 * The new value after the command or edit.
 */
export interface AuditActivityAuditPostData { 
    item: any | null;
    schema: DataTypeMetaSchema;
}

