/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space';
import { Equipment } from './equipment';
import { AuditActivityAudit } from './auditActivityAudit';


/**
 * An audit activity.
 */
export interface AuditActivity { 
    /**
     * The identifier of the activity.
     */
    id: string;
    /**
     * The fully qualified reference of the object.
     */
    itemReference: string;
    /**
     * The name of the object.
     */
    objectName: string;
    /**
     * The identifier of the object that generated this activity.
     */
    objectId: string;
    /**
     * A link to the object that generated this activity.
     */
    objectUrl: string;
    /**
     * The date-time representing the time when a user discarded the activity. This property will only be present if the `activityManagementStatus` of the alarm or audit for the activity is `discarded`. 
     */
    discardedTime: string | null;
    /**
     * The date-time for when the activity was detected.
     */
    creationTime: string;
    /**
     * The collection of spaces associated with the object on which the activity occurred. 
     */
    spaces?: Array<Space>;
    /**
     * The collection of equipment associated with the object on which the activity occurred. 
     */
    equipment?: Array<Equipment>;
    /**
     * The activity management status of the audit. The values of this property are:  - `pending` - Indicates a user has not yet acted upon the audit. - `discarded` - Indicates a user has acted upon or dismissed the audit. 
     */
    activityManagementStatus: AuditActivity.ActivityManagementStatusEnum;
    audit: AuditActivityAudit;
}
export namespace AuditActivity {
    export const ActivityManagementStatusEnum = {
        Pending: 'pending',
        Discarded: 'discarded'
    } as const;
    export type ActivityManagementStatusEnum = typeof ActivityManagementStatusEnum[keyof typeof ActivityManagementStatusEnum];
}


