/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnyDataTypeSchemaRequired } from './anyDataTypeSchemaRequired';
import { AuditActivityAuditPostData } from './auditActivityAuditPostData';
import { AuditActivityAuditPreData } from './auditActivityAuditPreData';
import { AuditActivityAuditSignature } from './auditActivityAuditSignature';


export interface AuditActivityAudit { 
    /**
     * A more detailed description of the audited action.
     */
    description?: string | null;
    /**
     * The Metasys application or component that generated the audit.   The values for this property come from the `auditOriginAppEnumSet` enumeration. Find the definition of `auditOriginAppEnumSet` at the relative URL of `/schemas/enums/auditOriginAppEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    originApplication: string;
    /**
     * The type of action audited by the system.  The values for this property come from the `auditActionTypeEnumSet` enumeration. Find the definition of `auditActionTypeEnumSet` at the relative URL of `/schemas/enums/auditActionTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    actionType: string;
    /**
     * Parameters passed for commands or writes.
     */
    parameters?: Array<AnyDataTypeSchemaRequired> | null;
    /**
     * The username of the user that initiated the action.
     */
    user: string | null;
    signature?: AuditActivityAuditSignature | null;
    /**
     * The level at which the system generated the audit.  The values for this property come from the `auditClassesEnumSet` enumeration. Find the definition of `auditClassesEnumSet` at the relative URL of `/schemas/enums/auditClassesEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    classLevel: string;
    /**
     * The status of the action.  The values for this property come from the `statusEnumSet` enumeration. Find the definition of `statusEnumSet` at the relative URL of `/schemas/enums/statusEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    status: string | null;
    /**
     * Error message for the action.
     */
    errorString: string | null;
    preData: AuditActivityAuditPreData;
    postData: AuditActivityAuditPostData;
    /**
     * A link to the available annotations available for the audit. 
     */
    annotationsUrl: string;
    /**
     * The total number of annotations associated with this audit. 
     */
    annotationsCount: number;
    /**
     * The total number of MVE Annotations associated with this audit. 
     */
    signedAnnotationsCount?: number;
    /**
     * A link to the audit.
     */
    self: string;
}

