/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditAnnotation } from './auditAnnotation';


export interface AuditAnnotations { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * Collection of annotations.
     */
    items: Array<AuditAnnotation>;
    /**
     * A link to the next page of results.
     */
    next: string | null;
    /**
     * A link to the previous page of results.
     */
    previous: string | null;
    /**
     * A link to this annotation collection.
     */
    self: string;
}

