/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space';
import { AnyDataTypeSchemaRequired } from './anyDataTypeSchemaRequired';
import { Equipment } from './equipment';
import { AuditPreData } from './auditPreData';
import { Signature } from './signature';
import { AuditPostData } from './auditPostData';


export interface Audit { 
    /**
     * The identifier of the audit.
     */
    id: string;
    /**
     * The fully qualified reference of the object.
     */
    itemReference: string;
    /**
     * The name of the object.
     */
    objectName: string;
    /**
     * A link to the object.
     */
    objectUrl: string;
    /**
     * A more detailed description of the audited action.
     */
    description: string | null;
    /**
     * The activity management status of this item.  The values of this property are described as follows:  - `pending` - Indicates the activity has yet to be acted upon. - `discarded` - Indicates that the activity has been acted upon or   deemed invalid by a user. 
     */
    activityManagementStatus: Audit.ActivityManagementStatusEnum;
    /**
     * The date-time representing when the user discarded this activity. 
     */
    discardedTime?: string | null;
    /**
     * The date-time when the system audited the action. 
     */
    creationTime: string;
    /**
     * The Metasys application or component that generated the audit.   The values for this property come from the `auditOriginAppEnumSet` enumeration. Find the definition of `auditOriginAppEnumSet` at the relative URL of `/schemas/enums/auditOriginAppEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    originApplication: string;
    /**
     * The type of action audited by the system.  The values for this property come from the `auditActionTypeEnumSet` enumeration. Find the definition of `auditActionTypeEnumSet` at the relative URL of `/schemas/enums/auditActionTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    actionType: string;
    /**
     * Parameters passed for audited commands or writes.
     */
    parameters?: Array<AnyDataTypeSchemaRequired> | null;
    /**
     * The username of the user that initiated the audited action.
     */
    user: string | null;
    signature?: Signature | null;
    /**
     * The level at which the system generated this audit.  The values for this property come from the `auditClassesEnumSet` enumeration. Find the definition of `auditClassesEnumSet` at the relative URL of `/schemas/enums/auditClassesEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    classLevel: string;
    /**
     * The status of the audited action.  The values for this property come from the `statusEnumSet` enumeration. Find the definition of `statusEnumSet` at the relative URL of `/schemas/enums/statusEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    status: string | null;
    /**
     * Error message for the audited action.
     */
    errorString: string | null;
    preData: AuditPreData;
    postData: AuditPostData;
    /**
     * The collection of spaces associated with the object on which the activity occurred. 
     */
    spaces?: Array<Space>;
    /**
     * The collection of equipment associated with the object on which the activity occurred. 
     */
    equipment?: Array<Equipment>;
    /**
     * A link to the annotations available on the audit.
     */
    annotationsUrl: string;
    /**
     * The total number of annotations associated with the audit.
     */
    annotationsCount: number;
    /**
     * The total number of MVE Annotations associated with the audit. 
     */
    signedAnnotationsCount?: number;
    /**
     * A link to this audit.
     */
    self: string;
}
export namespace Audit {
    export const ActivityManagementStatusEnum = {
        Pending: 'pending',
        Discarded: 'discarded'
    } as const;
    export type ActivityManagementStatusEnum = typeof ActivityManagementStatusEnum[keyof typeof ActivityManagementStatusEnum];
}


