/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditsUsers { 
    /**
     * The total number of usernames in the collection.
     */
    total: number;
    /**
     * Collection of unique usernames in audits.
     */
    items: Array<string>;
    /**
     * A link to this collection.
     */
    self: string;
}

