/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A command description.
 */
export interface CommandEntry { 
    /**
     * The command identifier  The values for this property come from the `commandIdEnumSet` enumeration. Find the definition of `commandIdEnumSet` at the relative URL of `/schemas/enums/commandIdEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    id: string;
    /**
     * The URL used to invoke this command. Commands are always invoked with a `PUT` method. 
     */
    invokeUrl: string;
    /**
     * Describes acceptable payloads for this command. While the schemas for commands vary they share some things in common. A command payload is always a JSON object. Typical properties include `parameters`, `priority` and `annotation`.  If `parameters` is present, it will provide a list of the parameters necessary to invoke the command (along with their types). The `parameters` property is always an array (even if it is empty or only has one parameter).  If `priority` is present, it will allow a command to be sent at a certain priority. Acceptable values for this property come from the `writePriorityEnumSet` enumeration.  If `annotation` is present, it will allow a note to be attached to the invocation of this command and this note will be visible in the system (attached to audits, for example). 
     */
    commandBodySchema: object;
    /**
     * Translated name of this command.
     */
    title?: string;
    /**
     * Will always be missing or set to `false`.
     */
    aggregateCommand?: boolean;
}

