/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The condition flags for one of the attributes in the `item`
 */
export interface ConditionValue { 
    /**
     * This condition applies only to prioritized attributes. It contains the current priority of the attribute. This condition is not listed if it doesn\'t apply to an attribute or if the condition has its default value.   The values for this property come from the `writePriorityEnumSet` enumeration. Find the definition of `writePriorityEnumSet` at the relative URL of `/schemas/enums/writePriorityEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    priority?: string;
    /**
     * This condition contains the current reliability of the attribute. This condition is not listed if it has its default value.   The values for this property come from the `reliabilityEnumSet` enumeration. Find the definition of `reliabilityEnumSet` at the relative URL of `/schemas/enums/reliabilityEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    reliability?: string;
    /**
     * This condition contains the current status of the attribute. This condition is not listed if it has its default value.   The values for this property come from the `objectStatusEnumSet` enumeration. Find the definition of `objectStatusEnumSet` at the relative URL of `/schemas/enums/objectStatusEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    status?: string;
    /**
     * This condition contains any error that occurred while trying to read an attribute. This condition is not listed if it has its default value.   The values for this property come from the `statusEnumSet` enumeration. Find the definition of `statusEnumSet` at the relative URL of `/schemas/enums/statusEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    error?: string;
}

