/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DateAndTime { 
    /**
     * The local date and time when the alarm was generated. (The value is local with respect to the device that generated the alarm.) An example value is `\"2024-10-11T19:49:23\"` 
     */
    dateTime?: string;
}

