/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the ability for the current user to take action on a given alarm. 
 */
export interface EffectivePermission { 
    /**
     * The ID of the alarm that these permissions apply to.
     */
    id: string;
    /**
     * Indicates whether the alarm can be acknowledged by the current user. 
     */
    canAcknowledge: boolean;
    /**
     * Indicates whether the alarm can be discarded by the current user. 
     */
    canDiscard: boolean;
    /**
     * Indicates whether the alarm can be annotated by the current user. This may be absent if the current platform does not support annotations. 
     */
    canAnnotate?: boolean;
}

