/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the commands that can be invoked by the current user.
 */
export interface EffectivePermissions { 
    /**
     * The list of commands the current user can invoke.
     */
    canInvoke: Array<string>;
}

