/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EquipmentTreeFolder } from './equipmentTreeFolder';
import { EquipmentTreeEquipment } from './equipmentTreeEquipment';


/**
 * @type EquipmentTreeFolderItemsInner
 * @export
 */
export type EquipmentTreeFolderItemsInner = EquipmentTreeEquipment | EquipmentTreeFolder;

