/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An equipment instance associated with the object on which the activity occurred. 
 */
export interface Equipment { 
    /**
     * The identifier of the equipment instance.
     */
    id: string;
    /**
     * The fully qualified reference of the equipment instance.
     */
    itemReference: string;
    /**
     * The name of the equipment instance.
     */
    equipmentName: string;
    /**
     * The name of the mapped point.
     */
    shortName: string;
    /**
     * The URL to the equipment instance.
     */
    equipmentUrl: string;
}

