/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EquipmentItemLegacy } from './equipmentItemLegacy';


export interface EquipmentItemsLegacy { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * Collection of equipment.
     */
    items: Array<EquipmentItemLegacy>;
    /**
     * A link to the next page of results.
     */
    next: string | null;
    /**
     * A link to the previous page of results.
     */
    previous: string | null;
    /**
     * A link to this equipment collection.
     */
    self: string;
}

