/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EquipmentTreeFolderItemsInner } from './equipmentTreeFolderItemsInner';


export interface EquipmentTreeFolder { 
    /**
     * A link to this equipment tree item, either an equipment instance or a folder.
     */
    readonly self?: string;
    /**
     * The identifier of the equipment tree item.
     */
    id?: string;
    /**
     * The name of the equipment instance or folder.
     */
    name?: string;
    /**
     * The fully qualified reference of the equipment.
     */
    itemReference?: string;
    /**
     * The object type of the equipment tree folder. This will always be `objectTypeEnumSet.containerClass`.   The values for this property come from the `objectTypeEnumSet` enumeration. Find the definition of `objectTypeEnumSet` at the relative URL of `/schemas/enums/objectTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    objectType?: EquipmentTreeFolder.ObjectTypeEnum;
    /**
     * Indicates if the equipment tree folder has children. 
     */
    hasChildren?: boolean;
    /**
     * A collection of equipment tree items, either equipment instances or folders, that are children of the equipment tree folder. 
     */
    items?: Array<EquipmentTreeFolderItemsInner>;
}
export namespace EquipmentTreeFolder {
    export const ObjectTypeEnum = {
        ObjectTypeEnumSetContainerClass: 'objectTypeEnumSet.containerClass'
    } as const;
    export type ObjectTypeEnum = typeof ObjectTypeEnum[keyof typeof ObjectTypeEnum];
}


