/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EquipmentPointsItemsInner } from './equipmentPointsItemsInner';


/**
 * The collection of points mapped to the equipment.
 */
export interface EquipmentPoints { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * The collection of equipment point mappings.
     */
    items: Array<EquipmentPointsItemsInner>;
    /**
     * A link to the next page of results.
     */
    next: string | null;
    /**
     * A link to the previous page of results.
     */
    previous: string | null;
    /**
     * A link to this equipment point mapping collection.
     */
    self: string;
}

