/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EquipmentTreeEquipment { 
    /**
     * A link to this equipment tree item, either an equipment instance or a folder.
     */
    readonly self?: string;
    /**
     * The identifier of the equipment tree item.
     */
    id?: string;
    /**
     * The name of the equipment instance or folder.
     */
    name?: string;
    /**
     * The fully qualified reference of the equipment.
     */
    itemReference?: string;
    /**
     * The name of the equipment definition for this equipment instance. If this instance is not associated with an equipment definition, this value will be null.
     */
    type?: string | null;
    /**
     * The object type of the equipment tree item. This will always be `objectTypeEnumSet.equipmentClass`.   The values for this property come from the `objectTypeEnumSet` enumeration. Find the definition of `objectTypeEnumSet` at the relative URL of `/schemas/enums/objectTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    objectType?: EquipmentTreeEquipment.ObjectTypeEnum;
    /**
     * The system subtype of the equipment definition for this equipment instance. If this instance is not associated with an equipment definition, this value will be null.  The values for this property come from the `subsystemCategoryEnumSet` enumeration. Find the definition of `subsystemCategoryEnumSet` at the relative URL of `/schemas/enums/subsystemCategoryEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    subsystemCategory?: string | null;
    /**
     * The identifier of the equipment definition for this equipment instance. If this instance is not associated with an equipment definition, this value will be null.
     */
    equipmentDefinitionId?: string | null;
}
export namespace EquipmentTreeEquipment {
    export const ObjectTypeEnum = {
        ObjectTypeEnumSetEquipmentClass: 'objectTypeEnumSet.equipmentClass'
    } as const;
    export type ObjectTypeEnum = typeof ObjectTypeEnum[keyof typeof ObjectTypeEnum];
}


