/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EquipmentItemLegacy { 
    /**
     * The identifier of the object.
     */
    id: string;
    /**
     * The fully qualified reference of the object.
     */
    itemReference: string;
    /**
     * The full name of the equipment instance.
     */
    name: string;
    /**
     * The name of the equipment definition for this equipment instance. If this instance is not associated with an equipment definition, this value will be null.
     */
    type: string | null;
    /**
     * <span style=\"color: #92989b; font-size: 13px\">RELEASE</span>:<span style=\"color: #d41f1c;\"> <strong>15.0</strong></span>\\ Indicates if the equipment instance has upstream equipment that serves it. 
     */
    hasUpstreamEquipment?: boolean;
    /**
     * A link to this equipment instance.
     */
    self: string;
    /**
     * A link to the spaces served by this equipment instance.
     */
    spacesUrl: string;
    /**
     * A link to the equipment served by this equipment instance.
     */
    equipmentUrl: string;
    /**
     * A link to the equipment that serves this equipment instance.
     */
    upstreamEquipmentUrl: string;
    /**
     * A link to the network devices that host this equipment instance.
     */
    networkDevicesUrl: string;
    /**
     * A link to the point mappings defined by this equipment instance.
     */
    pointsUrl: string;
}

