/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Additional details about the error.
 */
/**
 * @type ErrorResponseErrorDetails
 * Additional details about the error.
 * @export
 */
export type ErrorResponseErrorDetails = object | string;

