/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseErrorDetails } from './errorResponseErrorDetails';


export interface ErrorResponseError { 
  [key: string]: any | any;


    /**
     * A Metasys specific status code. The format of this code is variable. If the value is _unqualified_ ({enumValue}, e.g. \"attributeNotFound\"), then the display text associated to the code comes from the `statusEnumSet` available at `/schemas/enums/statusEnumSet`. If the value is qualified with just an enumeration (\"{enumeration}.{member}\", e.g. \"statusEnumSet.attributeNotFound\"), then the display text comes from the enumeration schema available at `/schemas/enums/{enumeration}`. If the value is qualified with a namespace (\"{namespace}:{enumeration}.{member}\", e.g. \"api.diagram:error.saveFailed\"), then the display text is the responsibility of the client. 
     */
    statusName?: string;
    /**
     * The display string message that correlates to `statusName`.
     */
    message?: string;
    details?: ErrorResponseErrorDetails;
}

