/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandEntry } from './commandEntry';
import { AggregateCommandSet } from './aggregateCommandSet';


/**
 * @type GetObjectCommands200ResponseItemsInner
 * @export
 */
export type GetObjectCommands200ResponseItemsInner = AggregateCommandSet | CommandEntry;

