/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetObjectAttributes200ResponseSchemaPropertiesValue { 
  [key: string]: any | any;


    /**
     * The localized name of the property
     */
    title?: string;
    /**
     * The JSON type of the property
     */
    type?: string;
    /**
     * The Metasys type of the property
     */
    metasysType?: string;
    /**
     * Indicates if the property is read-only or editable
     */
    readOnly?: boolean;
    /**
     * Indicates if the property is prioritized (which means it supports writing/commanding at different priorities)
     */
    prioritized?: boolean;
}

