/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Classification } from './classification';


export interface GetObjectSupportedChildTypes200ResponseInner { 
    /**
     * The type of the object.  The values for this property come from the `objectTypeEnumSet` enumeration. Find the definition of `objectTypeEnumSet` at the relative URL of `/schemas/enums/objectTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    readonly objectType?: string;
    /**
     * The translated name of the object
     */
    readonly description?: string;
    /**
     * The version of the object. This is typically of limited use as version numbers are not updated for most objects.
     */
    readonly version?: string;
    /**
     * Indicates if current client can create this type of object.
     */
    readonly isAuthorized?: boolean;
    classification?: Classification;
}
export namespace GetObjectSupportedChildTypes200ResponseInner {
}


