/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConditionValue } from './conditionValue';
import { EffectivePermissions } from './effectivePermissions';
import { ViewsInner } from './viewsInner';


export interface GetObject200Response { 
    /**
     * A link to this object.
     */
    readonly self: string;
    /**
     * The type of this object as defined by the `objectTypeEnumSet`.
     */
    readonly objectType: string;
    /**
     * A link to the parent of this object. All objects except the root object have a value for this property.
     */
    readonly parentUrl: string | null;
    /**
     * A link to the children of this object. You can use the `depth` parameter to this URL to get more than the immediate children of this object.
     */
    readonly objectsUrl: string;
    /**
     * A link to the network device that contains this object.
     */
    readonly networkDeviceUrl: string;
    /**
     * A link to all equipment point mappings defined for this object.
     */
    readonly pointsUrl: string;
    /**
     * A link to the list of attributes on this object for which samples are available.
     */
    readonly trendedAttributesUrl: string;
    /**
     * A link to the alarms generated by this object.
     */
    readonly alarmsUrl: string;
    /**
     * A link to the audits generated for this object.
     */
    readonly auditsUrl: string;
    /**
     * The `item` section of the response contains the attribute values for the requested view. The properties of this object vary based on the object and view requested. 
     */
    item: { [key: string]: any; };
    /**
     * If included in the response, this is the JSON schema that describes the properties of the `item` property 
     */
    readonly schema?: object;
    /**
     * This property contains condition flags (if any are set) for the properties of `item`. If none of the properties have any condition flags set, then `condition` will not be included in the response or it will be empty. 
     */
    readonly condition?: { [key: string]: ConditionValue; };
    /**
     * A nested collection of logical property groupings used for display purposes only.
     */
    views: Array<ViewsInner>;
    effectivePermissions: EffectivePermissions;
}

