/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetObjectsResponseEffectivePermissions { 
    /**
     * A list of identifiers for objects in the payload that the current user can delete. 
     */
    canDelete: Array<string>;
    /**
     * A list of identifiers for objects in the payload that the current user can view. 
     */
    canView: Array<string>;
    /**
     * A list of identifiers for objects in the current payload that the current user can modify. 
     */
    canModify: Array<string>;
}

