/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetObjectCommands200ResponseItemsInner } from './getObjectCommands200ResponseItemsInner';
import { EffectivePermissions } from './effectivePermissions';


export interface GetObjectCommands200Response { 
    /**
     * A link to this collection.
     */
    readonly self: string;
    /**
     * The list of commands. 
     */
    items: Array<GetObjectCommands200ResponseItemsInner>;
    effectivePermissions: EffectivePermissions;
}

