/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetObjectViews200ResponseItemsInner { 
    /**
     * The identifier of the view.  The values for this property come from the `viewNameEnumSet` enumeration. Find the definition of `viewNameEnumSet` at the relative URL of `/schemas/enums/viewNameEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    readonly id: string;
    /**
     * The link to use to request this view.
     */
    readonly viewUrl: string;
}

