/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetObjectAttributes200ResponseSchema } from './getObjectAttributes200ResponseSchema';


export interface GetObjectAttributes200Response { 
    item?: object;
    schema: GetObjectAttributes200ResponseSchema;
}

