/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectEntityInTree } from './objectEntityInTree';
import { Classification } from './classification';
import { ObjectMinimalList } from './objectMinimalList';


/**
 * @type GetObjectsResponseItemsInner
 * @export
 */
export type GetObjectsResponseItemsInner = ObjectEntityInTree | ObjectMinimalList;

