/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetObjectViews200ResponseItemsInner } from './getObjectViews200ResponseItemsInner';


export interface GetObjectViews200Response { 
    /**
     * The collection of views.
     */
    readonly items: Array<GetObjectViews200ResponseItemsInner>;
    /**
     * The link to this collection of views.
     */
    readonly self: string;
}

