/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricalTimeSeriesRecordInner } from './historicalTimeSeriesRecordInner';


export interface HistoricalTimeSeriesList { 
    /**
     * A link to this payload
     */
    readonly self: string;
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * A link to the next page of results.
     */
    next: string | null;
    /**
     * A link to the previous page of results.
     */
    previous: string | null;
    items: Array<HistoricalTimeSeriesRecordInner>;
}

