/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <span style=\"color: #92989b; font-size: 13px\">RELEASE</span>:<span style=\"color: #d41f1c;\"> <strong>15.0</strong></span>\\ An incomplete network device is a network device that has not been fully populated with all of its properties. This is typically the case when the network device is not reachable or when the API is unable to retrieve all of the properties of the network device. 
 */
export interface IncompleteNetworkDevice { 
    /**
     * The identifier of the network device.
     */
    id: string;
    /**
     * The fully qualified reference of the network device.
     */
    itemReference: string;
    /**
     * The full name of the network device.
     */
    name: string;
    /**
     * The link to the network device.
     */
    self: string;
    /**
     * A link to the network devices that are children of this network device.
     */
    networkDevicesUrl: string;
    /**
     * A link to the equipment instances hosted by this network device.
     */
    equipmentUrl: string;
    /**
     * A link to the spaces that are served by this network device.
     */
    spacesUrl: string;
    /**
     * A link to the objects contained within this network device.
     */
    objectsUrl: string;
    /**
     * A link to the attributes on this network device for which samples are available.
     */
    trendedAttributesUrl: string;
    /**
     * A link to the alarms available for this network device.
     */
    alarmsUrl: string;
}

