/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginRequest { 
    /**
     * The user name of an account. This can either be a local Metasys account, or an Active Directory account that has been granted access to Metasys. When using an Active Directory account, the value should be in the format `{name}@{domain}` (for example, `jane-doe@mycorp.com`).  **Note:** Only accounts with an _Access Type_ of `API` can be used to request a token from the REST API. 
     */
    username?: string;
    /**
     * The corresponding password of a Metasys account.
     */
    password?: string;
}

