/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncompleteNetworkDevice } from './incompleteNetworkDevice';
import { NetworkDevicePairing } from './networkDevicePairing';
import { NetworkDevice } from './networkDevice';


/**
 * @type NetworkDevicesItemsInner
 * @export
 */
export type NetworkDevicesItemsInner = IncompleteNetworkDevice | NetworkDevice;

