/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkDevicePairing } from './networkDevicePairing';


export interface NetworkDevice { 
    /**
     * The identifier of the network device.
     */
    id: string;
    /**
     * The fully qualified reference of the network device.
     */
    itemReference: string;
    /**
     * The full name of the network device.
     */
    name: string;
    /**
     * The type of this network device as defined by the `objectTypeEnumSet`.  The values for this property come from the `objectTypeEnumSet` enumeration. Find the definition of `objectTypeEnumSet` at the relative URL of `/schemas/enums/objectTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    objectType: string;
    /**
     * The version of `objectType` that is used for this object.
     */
    readonly objectTypeVersion?: string;
    /**
     * The product version of the object.
     */
    readonly productVersion?: string;
    /**
     * The description for the network device.
     */
    description: string;
    /**
     * The firmware version for the network device. This property will be an empty string \"\" if the device does not support a firmware version.
     */
    firmwareVersion: string;
    /**
     * The authorization category for the network device.  The values for this property come from the `objectCategoryEnumSet` enumeration. Find the definition of `objectCategoryEnumSet` at the relative URL of `/schemas/enums/objectCategoryEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    objectCategory: string;
    /**
     * The time zone for the network device. This property will be `null` if the device does not support a time zone.  The values for this property come from the `timeZoneEnumSet` enumeration. Find the definition of `timeZoneEnumSet` at the relative URL of `/schemas/enums/timeZoneEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    timeZone: string | null;
    /**
     * The link to the network device.
     */
    self: string;
    /**
     * A link to the network device that is the parent of this network device.
     */
    parentUrl: string | null;
    /**
     * A link to the network devices that are children of this network device.
     */
    networkDevicesUrl: string;
    /**
     * A link to the equipment instances hosted by this network device.
     */
    equipmentUrl: string;
    /**
     * A link to the spaces that are served by this network device.
     */
    spacesUrl: string;
    /**
     * A link to the objects contained within this network device.
     */
    objectsUrl: string;
    /**
     * A link to the attributes on this network device for which samples are available.
     */
    trendedAttributesUrl: string;
    /**
     * A link to the alarms available for this network device.
     */
    alarmsUrl: string;
    /**
     * <span style=\"color: #92989b; font-size: 13px\">RELEASE</span>:<span style=\"color: #d41f1c;\"> <strong>15.0</strong></span>\\ Indicates if the network device allows HTTP communication. This property will be `false` if the device has blocked the HTTP port (port 80).
     */
    allowHttp?: boolean;
    /**
     * <span style=\"color: #92989b; font-size: 13px\">RELEASE</span>:<span style=\"color: #d41f1c;\"> <strong>15.0</strong></span>\\ The BACnet IP communication mode for the network device.  The values for this property come from the `ipCommModeEnumSet` enumeration. Find the definition of `ipCommModeEnumSet` at the relative URL of `/schemas/enums/ipCommModeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    jciIpCommMode?: string;
    /**
     * The IPv4 address of the network device. This will be `null` if the device does not support an IP address.
     */
    ipAddress: string | null;
    /**
     * <span style=\"color: #92989b; font-size: 13px\">RELEASE</span>:<span style=\"color: #d41f1c;\"> <strong>15.0</strong></span>\\ The IPv6 address of the network device. This will be `null` if the device does not support an IPv6 address.
     */
    deviceIpv6Address?: string | null;
    /**
     * The expiration date & time of the device\'s HTTPS certificate. This will be `null` if the device does not support HTTPS certificates or there is no certificate present. 
     */
    certificateExpirationDate: string | null;
    pairing: NetworkDevicePairing;
}

