/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provides indicators to the pairing capabilities of the network device.
 */
export interface NetworkDevicePairing { 
    /**
     * Indicates if the device supports the pairing operation.
     */
    supported: boolean;
    /**
     * Indicates if the device has been authenticated with the site director. This property will always be `false` if `supported` is `false`.
     */
    paired: boolean;
}

