/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Meta-data about the referenced object.
 */
export interface NullableObjectReferenceDefinitionReferencedObject { 
    /**
     * The name of the object.
     */
    objectName?: string;
    /**
     * A link to the object.
     */
    objectUrl?: string;
}

