/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A periodic event that indicates that one or more COV subscriptions are active. 
 */
export interface ObjectsStreamValuesHeartbeatImproved { 
    /**
     * COV subscription IDs that the notification applies to.
     */
    activeSubscriptions: Array<string>;
    /**
     * Current server time
     */
    dateTime: string;
}

