/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConditionValue } from './conditionValue';
import { ObjectsStreamValuesNotificationInnerItem } from './objectsStreamValuesNotificationInnerItem';


export interface ObjectsStreamValuesNotificationInner { 
    /**
     * <span style=\"color: #92989b; font-size: 13px\">RELEASES</span>:<span style=\"color: #d41f1c;\"> <strong>14.1 and 15.0</strong></span>\\ COV subscription IDs that the notification applies to
     */
    subscriptionId?: string;
    item: ObjectsStreamValuesNotificationInnerItem;
    /**
     * The attribute the notification applies to.  The values for this property come from the `attributeEnumSet` enumeration. Find the definition of `attributeEnumSet` at the relative URL of `/schemas/enums/attributeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    attribute: string;
    /**
     * This property contains condition flags (if any are set) for the properties of `item`. If none of the properties have any condition flags set, then `condition` will not be included in the response or it will be empty. 
     */
    readonly condition: { [key: string]: ConditionValue; };
}

