/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EffectivePermission } from './effectivePermission';
import { Alarm } from './alarm';


export interface ObjectAlarms { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * Collection of alarms.
     */
    items: Array<Alarm>;
    /**
     * A link to the object which generated the alarms.
     */
    objectUrl: string;
    /**
     * A collection of permissions that apply to the alarms in `items`. 
     */
    effectivePermissions: Array<EffectivePermission>;
    /**
     * A link to the next page of results.
     */
    next: string | null;
    /**
     * A link to the previous page of results.
     */
    previous: string | null;
    /**
     * A link to this alarm collection.
     */
    self: string;
}

