/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * New value information for the subscribed attributes with additional identifying information for the object the update applies to. 
 */
export interface ObjectsStreamValuesUpdateInnerItem { 
  [key: string]: any | any;


    /**
     * The id of the object the update applies to. 
     */
    id: string;
    /**
     * The fully qualified reference of the object the update applies to. 
     */
    itemReference: string;
}

