/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectsAttributeSamplesResponseItemsInner } from './objectsAttributeSamplesResponseItemsInner';


export interface ObjectsAttributeSamplesResponse { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * JSON Schema definition of the items property.
     */
    schema: object;
    /**
     * Collection of time series samples.
     */
    items: Array<ObjectsAttributeSamplesResponseItemsInner>;
    /**
     * A link to this collection of value samples.
     */
    self: string;
    /**
     * A link to the object that is collecting and storing the samples.
     */
    objectUrl: string;
    /**
     * The sampled attribute.
     */
    attribute: string;
}

