/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Identifying information for the object the notification applies to which a client can use to read the new value of the `attribute`. 
 */
export interface ObjectsStreamValuesNotificationInnerItem { 
    /**
     * The id of the object the notification applies to. 
     */
    id: string;
    /**
     * The fully qualified reference of the object the notification applies to. 
     */
    itemReference: string;
}

