/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchAlarmRequest { 
    /**
     * The new activity management status of the alarm.  The values of this property are described as follows:  - `acknowledged` - The alarm has been recognized and viewed by a   user. An alarm may only be acknowledged if   `activityManagementStatus` is currently `pending` and   `isAckRequired` is `true`. - `discarded` - The alarm has been acted upon and addressed by a   user. Once an alarm is discarded, it cannot be changed to any   other state. 
     */
    activityManagementStatus: PatchAlarmRequest.ActivityManagementStatusEnum;
    /**
     * The annotation associated with the change of alarm state.
     */
    annotationText?: string | null;
}
export namespace PatchAlarmRequest {
    export const ActivityManagementStatusEnum = {
        Acknowledged: 'acknowledged',
        Discarded: 'discarded'
    } as const;
    export type ActivityManagementStatusEnum = typeof ActivityManagementStatusEnum[keyof typeof ActivityManagementStatusEnum];
}


