/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchAuditRequest { 
    /**
     * The new activity management status of the audit.  The only accepted value of this property is `discarded` because it is the only valid activity management state transition for an audit. Once an audit is discarded, it cannot be changed to any other state. 
     */
    activityManagementStatus: PatchAuditRequest.ActivityManagementStatusEnum;
    /**
     * The annotation to associate with the change of audit state.
     */
    annotationText?: string | null;
}
export namespace PatchAuditRequest {
    export const ActivityManagementStatusEnum = {
        Discarded: 'discarded'
    } as const;
    export type ActivityManagementStatusEnum = typeof ActivityManagementStatusEnum[keyof typeof ActivityManagementStatusEnum];
}


