/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PointsItemsInner { 
    /**
     * The identifier of the mapped equipment instance.
     */
    id: string;
    /**
     * The fully qualified reference of the mapped equipment instance.
     */
    itemReference: string;
    /**
     * The full name of the mapped equipment instance.
     */
    equipmentName: string;
    /**
     * The short name for the equipment point.
     */
    shortName: string;
    /**
     * The label for the equipment point.
     */
    label: string;
    /**
     * The category for the equipment point. This is generally unused.
     */
    category: string;
    /**
     * Indicates that the equipment point should be shown to an end user more prominently than other points. This value can be configured via the Equipment Definition.
     */
    isDisplayData: boolean;
    /**
     * A link to the mapped equipment.
     */
    equipmentUrl: string;
    /**
     * A link to the mapped object.
     */
    objectUrl: string;
    /**
     * The attribute of the mapped object which the point\'s value represents.  The values for this property come from the `attributeEnumSet` enumeration. Find the definition of `attributeEnumSet` at the relative URL of `/schemas/enums/attributeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    attribute: string;
}

