/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostRepoBatchTimeSeries200ResponseResponsesInnerBody } from './postRepoBatchTimeSeries200ResponseResponsesInnerBody';


export interface PostRepoBatchTimeSeries200ResponseResponsesInner { 
    /**
     * One of the client supplied unique request identifiers from the request. This identifier is used to match the response to the correct operation in the request.
     */
    id: string;
    /**
     * The HTTP Status code returned for the corresponding operation.
     */
    status: number;
    body: PostRepoBatchTimeSeries200ResponseResponsesInnerBody;
}

