/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StandardErrorMessage } from './standardErrorMessage';


/**
 * The response body for the corresponding operation.  <!-- The body can vary. Some errors have no body even though it would be helpful. Others include a .Net aspnet MVC binding error. That has a CR written on it and I\'d rather not document it until the CR has been triaged. see G4CR-8556 which has a comment that docs may need updating based on triage. --> 
 */
/**
 * @type PostActivitiesBatch200ResponseResponsesInnerBody
 * The response body for the corresponding operation.  <!-- The body can vary. Some errors have no body even though it would be helpful. Others include a .Net aspnet MVC binding error. That has a CR written on it and I\'d rather not document it until the CR has been triaged. see G4CR-8556 which has a comment that docs may need updating based on triage. --> 
 * @export
 */
export type PostActivitiesBatch200ResponseResponsesInnerBody = StandardErrorMessage | object | string;

