/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostObjectsRequest { 
    /**
     * The ID of the parent object. The new object will be created under this object. 
     */
    parentId: string;
    /**
     * A string that is locally unique within the context of the parent object for identifying the new object. This string will be the last component of the `itemReference` of the newly created object. For example, assume you have a folder with an `itemReference` of `adx:oas/Programming`. Then you create an AV with a local unique identifier of `ZN-3-T` within that folder. The newly created object will have an `itemReference` of `adx:oas/Programming.ZN-3-T`.  The value must not contain any control characters or any of the following characters: `\" # \' * , . / : < > ? @ [ \\ ] |` 
     */
    localUniqueIdentifier: string;
    /**
     * The type of object to create.  The values for this property come from the `objectTypeEnumSet` enumeration. Find the definition of `objectTypeEnumSet` at the relative URL of `/schemas/enums/objectTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    objectType: string;
    /**
     * The `item` object is where you set the properties of the newly created object. Which properties can be set and their data types can be discovered by using the _Get schema for object type_ operation.  This property may or may not be required depending on the object you are creating. Some objects have defaults for all properties and require nothing to be set when creating them. Others have required properties that must be set at creation time. 
     */
    item?: object;
}

