/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostAuditAnnotationRequest { 
    /**
     * The text of the annotation to create. This must not be `null`, empty, nor only whitespace. Additionally, any surrounding whitespace will be trimmed.
     */
    text: string;
}

