/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestObjectInner } from './requestObjectInner';


export interface PostRepoBatchTimeSeriesRequest { 
    /**
     * The HTTP method to use for each request. This property is restricted to `GET` for this version of the API. 
     */
    method: PostRepoBatchTimeSeriesRequest.MethodEnum;
    /**
     * A collection of entries that represent the operations to invoke.
     */
    requests: Array<RequestObjectInner>;
}
export namespace PostRepoBatchTimeSeriesRequest {
    export const MethodEnum = {
        Get: 'GET'
    } as const;
    export type MethodEnum = typeof MethodEnum[keyof typeof MethodEnum];
}


