/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConditionValue } from './conditionValue';
import { PostObjectsBatch200ResponseResponsesInnerBodyOneOf } from './postObjectsBatch200ResponseResponsesInnerBodyOneOf';
import { GetObjectAttributeResponse } from './getObjectAttributeResponse';
import { LookupObjectIdentifierErrorResponse } from './lookupObjectIdentifierErrorResponse';
import { ErrorResponseError } from './errorResponseError';
import { ErrorResponse } from './errorResponse';


/**
 * The response body for the corresponding operation.
 */
/**
 * @type PostObjectsBatch200ResponseResponsesInnerBody
 * The response body for the corresponding operation.
 * @export
 */
export type PostObjectsBatch200ResponseResponsesInnerBody = ErrorResponse | GetObjectAttributeResponse | LookupObjectIdentifierErrorResponse | PostObjectsBatch200ResponseResponsesInnerBodyOneOf | string;

