/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostActivitiesBatch200ResponseResponsesInner } from './postActivitiesBatch200ResponseResponsesInner';


export interface PostActivitiesBatch200Response { 
    responses: Array<PostActivitiesBatch200ResponseResponsesInner>;
}

