/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostActivitiesBatch200ResponseResponsesInnerBody } from './postActivitiesBatch200ResponseResponsesInnerBody';


export interface PostActivitiesBatch200ResponseResponsesInner { 
    /**
     * One of the client-supplied unique request identifiers from the request. This identifier is used to match the response to the correct operation in the request.
     */
    id: string;
    /**
     * The HTTP Status code returned for the corresponding operation. Beside the [standard HTTP status codes](#section/Validation), the following status codes may also be returned:  - 400: Bad request. Changing the state of an activity   may fail for a few reasons:   - The request contains annotation text but the     associated object is validated. Activity generated     for a validated object doesn\'t support an     `annotationText` property in the request. 
     */
    status: number;
    body?: PostActivitiesBatch200ResponseResponsesInnerBody;
}

