/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostObjectsBatchRequestRequestsInner { 
    /**
     * A client supplied unique identifier for this request. The `id` values supplied by the client will be used to uniquely identify the responses that correspond to each request.
     */
    id: string;
    /**
     * A relative path (with respect to `/objects`) that identifies a resource for one of the supported operations.
     */
    relativeUrl: string;
    /**
     * The body for the request. This property is only used when the operation accepts/requires a body.  <!-- visibility:internal -->  (INTERNAL) The `body` is required for _Modify objects_ and _Send commands_.  <!-- visibility:public -->  When used the `body` should conform to the request body schema of the command being invoked. 
     */
    body?: object;
}

