/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostActivitiesBatchRequestRequestsInner { 
    /**
     * A client supplied unique identifier for this request. The `id` values supplied by the client will be used to uniquely identify the responses that correspond to each request.
     */
    id: string;
    /**
     * An absolute URL to a resource within either `audits` or `alarms`. Here are the possibilities.  - _An audit:_ Used when discarding an audit (for example,   `https://{hostname}/api/v6/audits/a2649aa8-f3eb-569e-ac7e-cb97a45d7b0e`). - _Annotations for an audit:_ Used when adding an   annotation to an audit (for example,   `https://{hostname}/api/v6/audits/a2649aa8-f3eb-569e-ac7e-cb97a45d7b0e/annotations`). - _An alarm:_ Used when acknowledging or discarding an   alarm (for example,   `https://{hostname}/api/v6/alarms/a2649aa8-f3eb-569e-ac7e-cb97a45d7b0e`). - _Annotations for an alarm:_ Used when adding an   annotation to an alarm (for example,   `https://{hostname}/api/v6/alarms/a2649aa8-f3eb-569e-ac7e-cb97a45d7b0e/annotations`).  **Note:** In all of the examples the URL references `audits` or `alarms` and not `activities`. 
     */
    requestUrl: string;
    /**
     * A body that is appropriate for the specified operation.
     */
    body?: object;
}

