/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepoAttributeSamplesResponseItemsInner } from './repoAttributeSamplesResponseItemsInner';
import { StandardErrorMessage } from './standardErrorMessage';
import { RepoAttributeSamplesResponse } from './repoAttributeSamplesResponse';


/**
 * The response body for the corresponding operation.
 */
/**
 * @type PostRepoBatchTimeSeries200ResponseResponsesInnerBody
 * The response body for the corresponding operation.
 * @export
 */
export type PostRepoBatchTimeSeries200ResponseResponsesInnerBody = RepoAttributeSamplesResponse | StandardErrorMessage;

