/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostRepoBatchTimeSeries200ResponseResponsesInner } from './postRepoBatchTimeSeries200ResponseResponsesInner';


export interface PostRepoBatchTimeSeries200Response { 
    /**
     * A collection of objects that represent the responses to the individual requests that were invoked.
     */
    responses: Array<PostRepoBatchTimeSeries200ResponseResponsesInner>;
}

