/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostActivitiesBatchRequestRequestsInner } from './postActivitiesBatchRequestRequestsInner';


export interface PostActivitiesBatchRequest { 
    /**
     * The HTTP method to use for each request.
     */
    method: PostActivitiesBatchRequest.MethodEnum;
    /**
     * A collection of entries that represent the operations to invoke.
     */
    requests: Array<PostActivitiesBatchRequestRequestsInner>;
}
export namespace PostActivitiesBatchRequest {
    export const MethodEnum = {
        Patch: 'PATCH',
        Post: 'POST',
        Get: 'GET'
    } as const;
    export type MethodEnum = typeof MethodEnum[keyof typeof MethodEnum];
}


