/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepoTrendedObjectResponseSampledAttributesInner } from './repoTrendedObjectResponseSampledAttributesInner';


export interface RepoTrendedObjectResponse { 
    /**
     * Id of trended object.
     */
    id: string;
    /**
     * Item reference of object Id.
     */
    itemReference: string;
    /**
     * Name of the object.
     */
    name: string;
    /**
     * The collection of available sample based on object Id.
     */
    sampledAttributes: Array<RepoTrendedObjectResponseSampledAttributesInner>;
    /**
     * A link to this collection.
     */
    self: string;
}

