/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepoAttributeSamplesResponseItemsInner } from './repoAttributeSamplesResponseItemsInner';


export interface RepoAttributeSamplesResponse { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * JSON Schema definition of the items array and its samples in this response.
     */
    schema: any | null;
    /**
     * Collection of time series samples.
     */
    items: Array<RepoAttributeSamplesResponseItemsInner>;
    /**
     * A link to the previous page of this set of value samples.
     */
    previous?: string | null;
    /**
     * A link to the next page of this set of value samples.
     */
    next?: string | null;
    /**
     * A link to this collection of value samples.
     */
    self: string;
    /**
     * A link to the object from which these samples were generated.
     */
    timeSeriesUrl: string;
    /**
     * The sampled attribute.  The values for this property come from the `attributeEnumSet` enumeration. Find the definition of `attributeEnumSet` at the relative URL of `/schemas/enums/attributeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    attribute: string;
}

