/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepoTrendedAttributesResponseItemsInner } from './repoTrendedAttributesResponseItemsInner';


export interface RepoTrendedAttributesResponse { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * The collection of available samples.
     */
    items: Array<RepoTrendedAttributesResponseItemsInner>;
    /**
     * A link to this collection.
     */
    self: string;
}

