/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestObjectInner { 
    /**
     * A client supplied unique identifier for this request. The `id` values supplied by the client will be used to uniquely identify the responses that correspond to each request.
     */
    id: string;
    /**
     * A relative path (with respect to `/timeSeries/`) that identifies a resource for one of the supported operations.
     */
    relativeUrl: string;
}

