/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SampledAttributes { 
    /**
     * The base URL to use for fetching samples of this attribute.
     */
    samplesUrl: string;
    /**
     * The attribute for which samples exist.  The values for this property come from the `attributeEnumSet` enumeration. Find the definition of `attributeEnumSet` at the relative URL of `/schemas/enums/attributeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    attribute: string;
}

