/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the ability for the current user to take action on a given audit. 
 */
export interface SchemasEffectivePermission { 
    /**
     * The ID of the audit that these permissions apply to.
     */
    id: string;
    /**
     * Indicates whether the audit can be discarded by the current user. 
     */
    canDiscard: boolean;
    /**
     * Indicates whether the audit can be annotated by the current user. This may be absent if the current platform doesn\'t support annotations. 
     */
    canAnnotate?: boolean;
}

