/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SequenceNumber { 
    /**
     * The sequence number associated with this alarm. An example is `345` 
     */
    sequenceNumber?: number;
}

