/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * <span style=\"color: #92989b; font-size: 13px\">RELEASE</span>:<span style=\"color: #d41f1c;\"> <strong>15.0</strong></span>\\ The signature associated with the activity.
 */
export interface Signature { 
    /**
     * The full name of the person signing the annotation.
     */
    fullName?: string;
    /**
     * The reason for the action requiring an annotation.
     */
    reason?: string;
}

