/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A space associated with the object on which the activity occurred. 
 */
export interface Space { 
    /**
     * The identifier of the space.
     */
    id: string;
    /**
     * The fully qualified reference of the space.
     */
    itemReference: string;
    /**
     * The name of the space.
     */
    name: string;
    /**
     * The URL to the space.
     */
    spaceUrl: string;
}

