/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpaceInTree { 
    /**
     * The identifier of the space.
     */
    id: string;
    /**
     * The name of the space.
     */
    name: string;
    /**
     * The type of the space.  The values for this property come from the `spaceTypesEnumSet` enumeration. Find the definition of `spaceTypesEnumSet` at the relative URL of `/schemas/enums/spaceTypesEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    type: string;
    /**
     * A link to the space.
     */
    self: string;
    /**
     * A link to the parent space of the space. This value is null if the space is the root space.
     */
    parentUrl: string | null;
    /**
     * A link to the collection spaces that are children of the space.
     */
    spacesUrl: string;
    /**
     * A link to the collection of equipment serving this space.
     */
    equipmentUrl: string;
    /**
     * A link to the collection of network devices which host points defined on equipment serving this space.
     */
    networkDevicesUrl: string;
    /**
     * The fully qualified reference of the space.
     */
    itemReference: string;
    /**
     * Collection of spaces.
     */
    items?: Array<SpaceInTree>;
    /**
     * This space has spaces that it contains. 
     */
    hasChild?: boolean;
}

