/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpaceInTree } from './spaceInTree';


export interface SpacesInTree { 
    /**
     * Collection of spaces.
     */
    items: Array<SpaceInTree>;
    /**
     * A link to this space tree.
     */
    self: string;
}

