/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A general error of the API.
 */
export interface StandardErrorMessage { 
    /**
     * A Metasys specific status code. The format of this code is variable. It uses namespace/qualified format for `statusName` values. If the value is qualified with just an enumeration (\"{namespace}:{enumeration}.{member}\", e.g. \"enum.core:statusEnumSet.attributeNotFound\"), then the display text comes from the enumeration schema available at `/schemas/enums/{enumeration}`. If the value is qualified with a namespace (\"{namespace}:{enumeration}.{member}\", e.g. \"api.diagram:error.saveFailed\"), then the display text is the responsibility of the client. 
     */
    code: string;
    /**
     * The display string message that correlates to `statusName`.
     */
    message: string;
    /**
     * An object containing specific details to the type of error. Each type of error may have different detail properties and value types. 
     */
    details?: object | null;
    /**
     * An error that is more detailed or a cause of the containing error. This allows for a recursive error structure which a client can digest to as much detail as they understand. This is mutually exclusive with `innerErrors`. 
     */
    innerError?: StandardErrorMessage;
    /**
     * A collection of errors that is more detailed or causes of the containing error. This allows for a recursive error structure which a client can digest to as much detail as they understand. This is mutually exclusive with `innerError`. 
     */
    innerErrors?: Array<StandardErrorMessage>;
}

