/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSeriesStreamErrorItemsInner } from './timeSeriesStreamErrorItemsInner';


/**
 * Indicates an error occurred with regards to an active samples subscription. 
 */
export interface TimeSeriesStreamError { 
    /**
     * List of all subscription Ids for this stream for whom errors have been generated.
     */
    subscriptionIds: Array<string>;
    /**
     * The display string message that provides information about the errors that have been generated.
     */
    readonly message: string;
    /**
     * The collection of available error items.
     */
    items: Array<TimeSeriesStreamErrorItemsInner>;
    /**
     * The total number of items in the collection
     */
    total: number;
}

