/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeSeriesStreamingSubscriptionRequestItemsInner { 
    /**
     * The identifier of the object.  If only `objectId` is specified and not `attributeId`, then trend objects which are objects that have an `objectType` of `trendLogClass`, `trendMapperClass`, `bacnetTrendLogExtClass`, `trendLogNoextensionClass`, `bacnetTrendLogClass` or `bacnetTrendLogMultipleClass` are only supported. 
     */
    objectId: string;
    /**
     * The identifier of the attribute.  The values for this property come from the `attributeEnumSet` enumeration. Find the definition of `attributeEnumSet` at the relative URL of `/schemas/enums/attributeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    attributeId?: string;
    /**
     * Filter samples by objects by supplying one or more `sampledById` values.  An attribute may have multiple objects sampling it. Use this parameter to subscribe to samples only from a specific object or set of objects. If no value is given for this parameter, then it will subscribe to samples from all of the objects sampling this attribute. 
     */
    sampledById?: Array<string>;
}

