/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSeriesStreamingSubscriptionRequestItemsInner } from './timeSeriesStreamingSubscriptionRequestItemsInner';


export interface TimeSeriesStreamingSubscriptionRequest { 
    /**
     * Collection of items to sign up for.
     */
    items?: Array<TimeSeriesStreamingSubscriptionRequestItemsInner>;
}

