/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeSeriesStreamErrorItemsInner { 
    /**
     * Guid of the sampledByObjectId for which error has occurred.
     */
    sampledByObjectId?: string;
    /**
     * A Metasys specific status code. The format of this code is variable. It uses namespace/qualified format for `statusName` values. If the value is qualified with just an enumeration (\"{namespace}:{enumeration}.{member}\", e.g. \"enum.core:statusEnumSet.attributeNotFound\"), then the display text comes from the enumeration schema available at `/schemas/enums/{enumeration}`. If the value is qualified with a namespace (\"{namespace}:{enumeration}.{member}\", e.g. \"api:error.internalFault\"), then the display text is the responsibility of the client. 
     */
    code?: string;
    /**
     * The display string message that correlates to `statusName`.
     */
    message?: string;
}

