/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates an error occurred with regards to an active samples async response subscription.
 */
export interface TimeSeriesStreamAsyncError { 
    /**
     * List of all subscriptionIds for this async stream which an error has been generated,
     */
    subscriptionIds: Array<string>;
    /**
     * The display string message that correlates to an error has occurred in async stream.
     */
    message: string;
}

