/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type TimeSeriesStreamUpdateItemsInnerValue
 * @export
 */
export type TimeSeriesStreamUpdateItemsInnerValue = boolean | number | string;

