/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates when a subscription has been cancelled for objects samples.
 */
export interface TimeSeriesStreamCancelled { 
    /**
     * List of all subscriptionIds for this stream which have been cancelled.
     */
    subscriptionIds: Array<string>;
    /**
     * The display string message that correlates to the subscriptions that have been cancelled.
     */
    message: string;
}

