/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSeriesStreamUpdateItemsInner } from './timeSeriesStreamUpdateItemsInner';


/**
 * Indicates new samples have been generated. Sample updates from multiple objects and attributes can be contained in a single event 
 */
export interface TimeSeriesStreamUpdate { 
    /**
     * List of all subscription IDs that the updates apply to for this stream
     */
    subscriptionIds: Array<string>;
    /**
     * The total number of items in the collection
     */
    total: number;
    /**
     * A collection of sample update information for the subscribed data with additional identifying information for the objects and attributes the updates apply to.
     */
    items: Array<TimeSeriesStreamUpdateItemsInner>;
}

