/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSeriesStreamEstablishedItemsInnerSampledObjectsInner } from './timeSeriesStreamEstablishedItemsInnerSampledObjectsInner';


export interface TimeSeriesStreamEstablishedItemsInner { 
    /**
     * The Id of the object generating the samples..
     */
    sampledByObjectId?: string;
    /**
     * Collection of sampled objects
     */
    sampledObjects?: Array<TimeSeriesStreamEstablishedItemsInnerSampledObjectsInner>;
}

