/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates that a samples async response is complete.
 */
export interface TimeSeriesStreamAsyncCompleted { 
    /**
     * List of all subscriptionIds for this async stream which has been completed.
     */
    subscriptionIds: Array<string>;
    /**
     * The display string message that correlates to the completion of an async samples response.
     */
    message: string;
}

