/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Time { 
    /**
     * The local time the alarm was generated. (The time is local with respect to the device that generated the alarm.) An example value is `\"19:49:23\"` 
     */
    time?: string;
}

