/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrendedAttributeResponse { 
    /**
     * A link to this collection of object value samples.
     */
    samplesUrl: string;
    /**
     * The attribute on which the samples were taken.
     */
    attribute: string;
    /**
     * A link to this collection.
     */
    self: string;
}

