/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendedAttributesResponseItemsInnerSampledByInner } from './trendedAttributesResponseItemsInnerSampledByInner';


export interface TrendedAttributesResponseItemsInner { 
    /**
     * A link to this collection of object value samples.
     */
    samplesUrl: string;
    /**
     * The attribute on which the samples were taken.  The values for this property come from the `attributeEnumSet` enumeration. Find the definition of `attributeEnumSet` at the relative URL of `/schemas/enums/attributeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    attribute: string;
    /**
     * JSON Schema of the attribute being sampled.
     */
    attributeSchema: object;
    /**
     * A list of objects that are sampling this attribute.
     */
    sampledBy: Array<TrendedAttributesResponseItemsInnerSampledByInner>;
}

