/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendedAttributesResponseItemsInner } from './trendedAttributesResponseItemsInner';


export interface TrendedAttributesResponse { 
    /**
     * The total number of items in the collection.
     */
    total: number;
    /**
     * The collection of available samples.
     */
    items: Array<TrendedAttributesResponseItemsInner>;
    /**
     * A link to this collection.
     */
    self: string;
}

