/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendedAttributesResponseItemsInnerSampledByInnerItem } from './trendedAttributesResponseItemsInnerSampledByInnerItem';


export interface TrendedAttributesResponseItemsInnerSampledByInner { 
    /**
     * A link to this object.
     */
    readonly self: string;
    item: TrendedAttributesResponseItemsInnerSampledByInnerItem;
}

