/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewsInnerViewsInnerViewsInner } from './viewsInnerViewsInnerViewsInner';


export interface ViewsInnerViewsInner { 
    /**
     * The values for this property come from the `groupTypeEnumSet` enumeration. Find the definition of `groupTypeEnumSet` at the relative URL of `/schemas/enums/groupTypeEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    id: string;
    title: string;
    views: Array<ViewsInnerViewsInnerViewsInner>;
}

