/**
 * Metasys REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewsInnerViewsInner } from './viewsInnerViewsInner';


export interface ViewsInner { 
    /**
     * The values for this property come from the `viewNameEnumSet` enumeration. Find the definition of `viewNameEnumSet` at the relative URL of `/schemas/enums/viewNameEnumSet`.  **See also:** * [Get enumeration](#operation/getEnumerationAsJsonSchema) for more information on retrieving an enumeration.
     */
    id: string;
    title: string;
    views: Array<ViewsInnerViewsInner>;
}

